CREATE TABLE IF NOT EXISTS t_user (
    ID_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    u_username varchar(255),
    u_delete varchar(255)
);

ALTER TABLE t_settings ADD COLUMN IF NOT EXISTS ID_user integer;
ALTER TABLE t_settings DROP CONSTRAINT IF EXISTS uq_t_settings_key;
DROP INDEX IF EXISTS idx_t_settings_key;
CREATE INDEX IF NOT EXISTS idx_t_settings_key_user ON t_settings (s_key, ID_user);
CREATE INDEX IF NOT EXISTS idx_t_user_username ON t_user (LOWER(u_username));
