-- Data exported from MySQL localhost/db_sriundee_shop for PostgreSQL.
-- Run after db_sriundee_shop_postgresql.sql.
BEGIN;
CREATE TABLE IF NOT EXISTS t_user (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    u_username varchar(255),
    u_delete varchar(255)
);
ALTER TABLE t_settings ADD COLUMN IF NOT EXISTS id_user integer;
ALTER TABLE t_income ADD COLUMN IF NOT EXISTS id_sale integer;
ALTER TABLE t_sale ADD COLUMN IF NOT EXISTS id_type integer;
ALTER TABLE t_sale ADD COLUMN IF NOT EXISTS id_art integer;
TRUNCATE TABLE t_group, t_artist, t_type, t_website, t_version, t_product_status, t_product, t_cover, t_product_web, t_type_cost, t_cost, t_cost_detail, t_type_income, t_income, t_lot, t_lot_detail, t_menu, t_payment_method, t_payment_type, t_order, t_order_status, t_order_detail, t_sale, t_settings, t_log_version, t_user RESTART IDENTITY CASCADE;

-- t_group: 5 rows
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (1, 'SM', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (2, 'YG', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (3, 'JYP', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (4, 'HYPE', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (5, 'อื่น ๆ', 'A');

-- t_artist: 4 rows
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (4, 'FLOW50-20260521-231255 ARTIST-A', 5, '', 'A');
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (5, 'FLOW50-20260521-231255 ARTIST-B', 5, '', 'A');
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (6, 'FLOW50-20260521-231255 ARTIST-C', 5, '', 'A');
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (7, 'STATUS20-20260522-002659 ARTIST', 5, '', 'A');

-- t_type: 4 rows
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (4, 'FLOW50-20260521-231255 ALBUM', 'A');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (5, 'FLOW50-20260521-231255 GOODS', 'A');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (6, 'FLOW50-20260521-231255 LIGHT', 'A');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (7, 'STATUS20-20260522-002659 TYPE', 'A');

-- t_website: 4 rows
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (4, 'FLOW50-20260521-231255 WEB-A', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (5, 'FLOW50-20260521-231255 WEB-B', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (6, 'FLOW50-20260521-231255 WEB-C', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (7, 'STATUS20-20260522-002659 WEB', 'A');

-- t_version: 4 rows
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (4, 4, 'FLOW50-20260521-231255 VER-A', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (5, 5, 'FLOW50-20260521-231255 VER-B', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (6, 6, 'FLOW50-20260521-231255 VER-C', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (7, 7, 'STATUS20-20260522-002659 VERSION', 'A');

-- t_product_status: 2 rows
INSERT INTO t_product_status (id_pro_status, ps_name) VALUES (1, 'เปิดพรี');
INSERT INTO t_product_status (id_pro_status, ps_name) VALUES (2, 'ปิดพรี');

-- t_product: 4 rows
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (4, 'FLOW50-20260521-231255 PRODUCT-A', 4, 4, '2026-05-29', '2026-06-13', 2, 'A', 'https://pbs.twimg.com/media/HI2UrzpaQAAiB0y?format=jpg&name=medium');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (5, 'FLOW50-20260521-231255 PRODUCT-B', 5, 5, '2026-06-05', '2026-06-22', 1, 'A', '');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (6, 'FLOW50-20260521-231255 PRODUCT-C', 6, 6, '2026-06-10', '2026-06-30', 1, 'A', '');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (7, 'STATUS20-20260522-002659 PRODUCT', 7, 7, '2026-07-31', '2026-08-15', 1, 'A', '');

-- t_cover: 4 rows
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (4, 4, 4, 4, 'FLOW50-20260521-231255 COVER-A', '1290', '500', '790', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (5, 5, 5, 5, 'FLOW50-20260521-231255 COVER-B', '890', '300', '590', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (6, 6, 6, 6, 'FLOW50-20260521-231255 COVER-C', '1590', '650', '940', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (7, 7, 7, 7, 'STATUS20-20260522-002659 COVER', '990', '350', '640', 'A');

-- t_product_web: 4 rows
INSERT INTO t_product_web (id_pro_web, id_pro, id_web) VALUES (4, 4, 4);
INSERT INTO t_product_web (id_pro_web, id_pro, id_web) VALUES (5, 5, 5);
INSERT INTO t_product_web (id_pro_web, id_pro, id_web) VALUES (6, 6, 6);
INSERT INTO t_product_web (id_pro_web, id_pro, id_web) VALUES (7, 7, 7);

-- t_type_cost: 6 rows
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (1, 'ค่ากดของ');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (2, 'ค่าชิปปิ้ง');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (3, 'ค่าสั่งกล่อง');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (4, 'ค่าสั่งทำของแถม');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (5, 'ค่าส่งไปรษณีย์');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (99, 'อื่น ๆ');

-- t_cost: 9 rows
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (1, '2026-05-18', 1, '68860', 'FLOW50-20260521-231255 press cost', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (2, '2026-06-01', 2, '4298', 'FLOW50-20260521-231255 shipping cost', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (3, '2026-06-03', 5, '833.1', 'FLOW50-20260521-231255 postal cost', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (4, '2026-06-04', 3, '150', 'FLOW50-20260521-231255 extra expense type 3', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (5, '2026-06-04', 4, '225', 'FLOW50-20260521-231255 extra expense type 4', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (6, '2026-06-04', 99, '300', 'FLOW50-20260521-231255 extra expense type 99', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (7, '2026-07-21', 1, '21235.5', 'STATUS20-20260522-002659 press cost', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (8, '2026-08-01', 2, '1386', 'STATUS20-20260522-002659 shipping cost', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (9, '2026-08-03', 5, '267.3', 'STATUS20-20260522-002659 postal cost', 'A');

-- t_cost_detail: 105 rows
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (1, 1, 11);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (2, 1, 12);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (3, 1, 13);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (4, 1, 14);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (5, 1, 15);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (6, 1, 16);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (7, 1, 17);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (8, 1, 18);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (9, 1, 19);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (10, 1, 20);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (11, 1, 21);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (12, 1, 22);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (13, 1, 23);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (14, 1, 24);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (15, 1, 25);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (16, 1, 26);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (17, 1, 27);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (18, 1, 28);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (19, 1, 29);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (20, 1, 30);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (21, 1, 31);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (22, 1, 32);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (23, 1, 33);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (24, 1, 34);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (25, 1, 35);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (26, 1, 36);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (27, 1, 37);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (28, 1, 38);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (29, 1, 39);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (30, 1, 40);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (31, 1, 41);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (32, 1, 42);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (33, 1, 43);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (34, 1, 44);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (35, 1, 45);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (36, 1, 46);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (37, 1, 47);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (38, 1, 48);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (39, 1, 49);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (40, 1, 50);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (41, 2, 31);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (42, 2, 32);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (43, 2, 33);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (44, 2, 34);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (45, 2, 35);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (46, 2, 36);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (47, 2, 37);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (48, 2, 38);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (49, 2, 39);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (50, 2, 40);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (51, 2, 41);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (52, 2, 42);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (53, 2, 43);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (54, 2, 44);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (55, 2, 45);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (56, 2, 46);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (57, 2, 47);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (58, 2, 48);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (59, 2, 49);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (60, 2, 50);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (61, 3, 41);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (62, 3, 42);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (63, 3, 43);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (64, 3, 44);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (65, 3, 45);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (66, 3, 46);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (67, 3, 47);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (68, 3, 48);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (69, 3, 49);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (70, 3, 50);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (71, 7, 51);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (72, 7, 52);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (73, 7, 53);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (74, 7, 54);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (75, 7, 55);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (76, 7, 56);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (77, 7, 57);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (78, 7, 58);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (79, 7, 59);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (80, 7, 60);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (81, 7, 61);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (82, 7, 62);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (83, 7, 63);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (84, 7, 64);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (85, 7, 65);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (86, 7, 66);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (87, 7, 67);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (88, 7, 68);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (89, 7, 69);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (90, 7, 70);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (91, 8, 61);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (92, 8, 62);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (93, 8, 63);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (94, 8, 64);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (95, 8, 65);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (96, 8, 66);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (97, 8, 67);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (98, 8, 68);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (99, 8, 69);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (100, 8, 70);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (101, 9, 66);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (102, 9, 67);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (103, 9, 68);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (104, 9, 69);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (105, 9, 70);

-- t_type_income: 4 rows
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (1, 'ค่าของ ( จ่ายเต็ม )');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (2, 'ค่าของ ( มัดจำ )');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (3, 'ยอดมัดจำที่เหลือ');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (4, 'ของพร้อมส่ง');

-- t_income: 80 rows
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (1, '2026-05-01', 'FLOW50-20260521-231255-CUS-001', 1, '1340', 'จ่ายเต็ม', 'A', 1, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (2, '2026-05-02', 'FLOW50-20260521-231255-CUS-002', 2, '600', 'จ่ายมัดจำ', 'A', 2, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (3, '2026-05-03', 'FLOW50-20260521-231255-CUS-003', 1, '4840', 'จ่ายเต็ม', 'A', 3, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (4, '2026-05-04', 'FLOW50-20260521-231255-CUS-004', 2, '2000', 'จ่ายมัดจำ', 'A', 4, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (5, '2026-05-05', 'FLOW50-20260521-231255-CUS-005', 1, '950', 'จ่ายเต็ม', 'A', 5, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (6, '2026-05-06', 'FLOW50-20260521-231255-CUS-006', 2, '1300', 'จ่ายมัดจำ', 'A', 6, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (7, '2026-05-07', 'FLOW50-20260521-231255-CUS-007', 1, '3900', 'จ่ายเต็ม', 'A', 7, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (8, '2026-05-08', 'FLOW50-20260521-231255-CUS-008', 2, '1200', 'จ่ายมัดจำ', 'A', 8, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (9, '2026-05-09', 'FLOW50-20260521-231255-CUS-009', 1, '1660', 'จ่ายเต็ม', 'A', 9, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (10, '2026-05-10', 'FLOW50-20260521-231255-CUS-010', 2, '1000', 'จ่ายมัดจำ', 'A', 10, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (11, '2026-05-11', 'FLOW50-20260521-231255-CUS-011', 1, '2730', 'จ่ายเต็ม', 'A', 11, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (12, '2026-05-12', 'FLOW50-20260521-231255-CUS-012', 2, '2600', 'จ่ายมัดจำ', 'A', 12, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (13, '2026-05-13', 'FLOW50-20260521-231255-CUS-013', 1, '1340', 'จ่ายเต็ม', 'A', 13, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (14, '2026-05-14', 'FLOW50-20260521-231255-CUS-014', 2, '600', 'จ่ายมัดจำ', 'A', 14, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (15, '2026-05-15', 'FLOW50-20260521-231255-CUS-015', 1, '4840', 'จ่ายเต็ม', 'A', 15, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (16, '2026-05-16', 'FLOW50-20260521-231255-CUS-016', 2, '2000', 'จ่ายมัดจำ', 'A', 16, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (17, '2026-05-17', 'FLOW50-20260521-231255-CUS-017', 1, '950', 'จ่ายเต็ม', 'A', 17, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (18, '2026-05-18', 'FLOW50-20260521-231255-CUS-018', 2, '1300', 'จ่ายมัดจำ', 'A', 18, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (19, '2026-05-19', 'FLOW50-20260521-231255-CUS-019', 1, '3920', 'จ่ายเต็ม', 'A', 19, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (20, '2026-05-20', 'FLOW50-20260521-231255-CUS-020', 2, '1200', 'จ่ายมัดจำ', 'A', 20, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (21, '2026-05-21', 'FLOW50-20260521-231255-CUS-021', 1, '1640', 'จ่ายเต็ม', 'A', 21, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (22, '2026-05-22', 'FLOW50-20260521-231255-CUS-022', 2, '1000', 'จ่ายมัดจำ', 'A', 22, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (23, '2026-05-23', 'FLOW50-20260521-231255-CUS-023', 1, '2730', 'จ่ายเต็ม', 'A', 23, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (24, '2026-05-24', 'FLOW50-20260521-231255-CUS-024', 2, '2600', 'จ่ายมัดจำ', 'A', 24, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (25, '2026-05-25', 'FLOW50-20260521-231255-CUS-025', 1, '1340', 'จ่ายเต็ม', 'A', 25, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (26, '2026-05-26', 'FLOW50-20260521-231255-CUS-026', 2, '600', 'จ่ายมัดจำ', 'A', 26, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (27, '2026-05-27', 'FLOW50-20260521-231255-CUS-027', 1, '4840', 'จ่ายเต็ม', 'A', 27, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (28, '2026-05-28', 'FLOW50-20260521-231255-CUS-028', 2, '2000', 'จ่ายมัดจำ', 'A', 28, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (29, '2026-05-01', 'FLOW50-20260521-231255-CUS-029', 1, '950', 'จ่ายเต็ม', 'A', 29, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (30, '2026-05-02', 'FLOW50-20260521-231255-CUS-030', 2, '1300', 'จ่ายมัดจำ', 'A', 30, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (31, '2026-05-03', 'FLOW50-20260521-231255-CUS-031', 1, '3920', 'จ่ายเต็ม', 'A', 31, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (32, '2026-05-04', 'FLOW50-20260521-231255-CUS-032', 2, '1200', 'จ่ายมัดจำ', 'A', 32, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (33, '2026-05-05', 'FLOW50-20260521-231255-CUS-033', 1, '1660', 'จ่ายเต็ม', 'A', 33, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (34, '2026-05-06', 'FLOW50-20260521-231255-CUS-034', 2, '1000', 'จ่ายมัดจำ', 'A', 34, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (35, '2026-05-07', 'FLOW50-20260521-231255-CUS-035', 1, '2710', 'จ่ายเต็ม', 'A', 35, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (36, '2026-05-08', 'FLOW50-20260521-231255-CUS-036', 2, '2600', 'จ่ายมัดจำ', 'A', 36, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (37, '2026-05-09', 'FLOW50-20260521-231255-CUS-037', 1, '1340', 'จ่ายเต็ม', 'A', 37, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (38, '2026-05-10', 'FLOW50-20260521-231255-CUS-038', 2, '600', 'จ่ายมัดจำ', 'A', 38, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (39, '2026-05-11', 'FLOW50-20260521-231255-CUS-039', 1, '4840', 'จ่ายเต็ม', 'A', 39, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (40, '2026-05-12', 'FLOW50-20260521-231255-CUS-040', 2, '2000', 'จ่ายมัดจำ', 'A', 40, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (41, '2026-05-13', 'FLOW50-20260521-231255-CUS-041', 1, '950', 'จ่ายเต็ม', 'A', 41, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (42, '2026-05-14', 'FLOW50-20260521-231255-CUS-042', 2, '1300', 'จ่ายมัดจำ', 'A', 42, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (43, '2026-05-15', 'FLOW50-20260521-231255-CUS-043', 1, '3920', 'จ่ายเต็ม', 'A', 43, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (44, '2026-05-16', 'FLOW50-20260521-231255-CUS-044', 2, '1200', 'จ่ายมัดจำ', 'A', 44, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (45, '2026-05-17', 'FLOW50-20260521-231255-CUS-045', 1, '1660', 'จ่ายเต็ม', 'A', 45, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (46, '2026-05-18', 'FLOW50-20260521-231255-CUS-046', 2, '1000', 'จ่ายมัดจำ', 'A', 46, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (47, '2026-05-19', 'FLOW50-20260521-231255-CUS-047', 1, '2730', 'จ่ายเต็ม', 'A', 47, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (48, '2026-05-20', 'FLOW50-20260521-231255-CUS-048', 2, '2600', 'จ่ายมัดจำ', 'A', 48, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (49, '2026-05-21', 'FLOW50-20260521-231255-CUS-049', 1, '1320', 'จ่ายเต็ม', 'A', 49, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (50, '2026-05-22', 'FLOW50-20260521-231255-CUS-050', 2, '600', 'จ่ายมัดจำ', 'A', 50, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (51, '2026-06-05', 'FLOW50-20260521-231255-CUS-002', 3, '1240', 'จ่ายมัดจำที่เหลือ', 'A', 2, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (52, '2026-06-05', 'FLOW50-20260521-231255-CUS-004', 3, '3210', 'จ่ายมัดจำที่เหลือ', 'A', 4, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (53, '2026-06-05', 'FLOW50-20260521-231255-CUS-006', 3, '1950', 'จ่ายมัดจำที่เหลือ', 'A', 6, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (54, '2026-06-05', 'FLOW50-20260521-231255-CUS-008', 3, '2420', 'จ่ายมัดจำที่เหลือ', 'A', 8, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (55, '2026-06-05', 'FLOW50-20260521-231255-CUS-010', 3, '1630', 'จ่ายมัดจำที่เหลือ', 'A', 10, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (56, '2026-06-05', 'FLOW50-20260521-231255-CUS-012', 3, '3830', 'จ่ายมัดจำที่เหลือ', 'A', 12, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (57, '2026-06-05', 'FLOW50-20260521-231255-CUS-014', 3, '1220', 'จ่ายมัดจำที่เหลือ', 'A', 14, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (58, '2026-06-05', 'FLOW50-20260521-231255-CUS-016', 3, '3210', 'จ่ายมัดจำที่เหลือ', 'A', 16, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (59, '2026-06-05', 'FLOW50-20260521-231255-CUS-018', 3, '1950', 'จ่ายมัดจำที่เหลือ', 'A', 18, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (60, '2026-06-05', 'FLOW50-20260521-231255-CUS-020', 3, '2420', 'จ่ายมัดจำที่เหลือ', 'A', 20, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (61, '2026-07-01', 'STATUS20-20260522-002659-CUS-001', 1, '1040', 'จ่ายเต็ม', 'A', 51, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (62, '2026-07-02', 'STATUS20-20260522-002659-CUS-002', 1, '2030', 'จ่ายเต็ม', 'A', 52, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (63, '2026-07-03', 'STATUS20-20260522-002659-CUS-003', 1, '3020', 'จ่ายเต็ม', 'A', 53, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (64, '2026-07-04', 'STATUS20-20260522-002659-CUS-004', 1, '1040', 'จ่ายเต็ม', 'A', 54, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (65, '2026-07-05', 'STATUS20-20260522-002659-CUS-005', 1, '2030', 'จ่ายเต็ม', 'A', 55, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (66, '2026-07-06', 'STATUS20-20260522-002659-CUS-006', 1, '3020', 'จ่ายเต็ม', 'A', 56, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (67, '2026-07-07', 'STATUS20-20260522-002659-CUS-007', 1, '1040', 'จ่ายเต็ม', 'A', 57, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (68, '2026-07-08', 'STATUS20-20260522-002659-CUS-008', 1, '2030', 'จ่ายเต็ม', 'A', 58, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (69, '2026-07-09', 'STATUS20-20260522-002659-CUS-009', 1, '3020', 'จ่ายเต็ม', 'A', 59, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (70, '2026-07-10', 'STATUS20-20260522-002659-CUS-010', 1, '1040', 'จ่ายเต็ม', 'A', 60, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (71, '2026-07-11', 'STATUS20-20260522-002659-CUS-011', 1, '2030', 'จ่ายเต็ม', 'A', 61, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (72, '2026-07-12', 'STATUS20-20260522-002659-CUS-012', 1, '3020', 'จ่ายเต็ม', 'A', 62, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (73, '2026-07-13', 'STATUS20-20260522-002659-CUS-013', 1, '1040', 'จ่ายเต็ม', 'A', 63, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (74, '2026-07-14', 'STATUS20-20260522-002659-CUS-014', 1, '2030', 'จ่ายเต็ม', 'A', 64, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (75, '2026-07-15', 'STATUS20-20260522-002659-CUS-015', 1, '3020', 'จ่ายเต็ม', 'A', 65, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (76, '2026-07-16', 'STATUS20-20260522-002659-CUS-016', 1, '1040', 'จ่ายเต็ม', 'A', 66, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (77, '2026-07-17', 'STATUS20-20260522-002659-CUS-017', 1, '2030', 'จ่ายเต็ม', 'A', 67, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (78, '2026-07-18', 'STATUS20-20260522-002659-CUS-018', 1, '3020', 'จ่ายเต็ม', 'A', 68, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (79, '2026-07-19', 'STATUS20-20260522-002659-CUS-019', 1, '1040', 'จ่ายเต็ม', 'A', 69, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (80, '2026-07-20', 'STATUS20-20260522-002659-CUS-020', 1, '2030', 'จ่ายเต็ม', 'A', 70, NULL);

-- t_lot: 2 rows
INSERT INTO t_lot (id_lot, l_lot_number, l_create_date, l_start_date, l_end_date, l_arrive_date, l_delete) VALUES (1, '01', '2026-05-20', '2026-05-25', '2026-05-31', '2026-06-01', 'A');
INSERT INTO t_lot (id_lot, l_lot_number, l_create_date, l_start_date, l_end_date, l_arrive_date, l_delete) VALUES (2, 'STATUS20-20260522-002659-LOT-01', '2026-07-22', '2026-07-25', '2026-07-31', '2026-08-01', 'A');

-- t_lot_detail: 45 rows
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (1, 1, 21);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (2, 1, 22);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (3, 1, 23);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (4, 1, 24);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (5, 1, 25);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (6, 1, 26);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (7, 1, 27);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (8, 1, 28);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (9, 1, 29);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (10, 1, 30);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (11, 1, 31);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (12, 1, 32);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (13, 1, 33);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (14, 1, 34);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (15, 1, 35);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (16, 1, 36);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (17, 1, 37);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (18, 1, 38);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (19, 1, 39);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (20, 1, 40);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (21, 1, 41);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (22, 1, 42);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (23, 1, 43);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (24, 1, 44);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (25, 1, 45);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (26, 1, 46);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (27, 1, 47);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (28, 1, 48);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (29, 1, 49);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (30, 1, 50);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (31, 2, 56);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (32, 2, 57);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (33, 2, 58);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (34, 2, 59);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (35, 2, 60);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (36, 2, 61);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (37, 2, 62);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (38, 2, 63);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (39, 2, 64);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (40, 2, 65);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (41, 2, 66);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (42, 2, 67);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (43, 2, 68);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (44, 2, 69);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (45, 2, 70);

-- t_menu: 17 rows
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (2, 'ข้อมูลพื้นฐาน', 'Y', NULL, NULL, 'bi bi-stack', 2);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (3, 'ข้อมูลศิลปิน', NULL, 2, '/artist', NULL, 1);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (4, 'ข้อมูลประเภทสินค้า', NULL, 2, '/type', NULL, 2);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (5, 'ข้อมูลเว็บไซต์', NULL, 2, '/website', NULL, 3);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (6, 'ข้อมูลสินค้า', 'N', NULL, '/product', 'bi bi-book-half', 4);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (7, 'บันทึกออร์เดอร์', 'N', NULL, '/order', 'bi bi-basket', 5);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (8, 'อัปเดทสถานะ', 'N', NULL, '/change', 'bi bi-check-circle-fill', 8);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (9, 'ข้อมูลการกดของ', 'N', NULL, '/check_status_2', 'bi bi-clipboard-check', 9);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (10, 'ข้อมูล LOT', 'N', NULL, '/lot', 'bi bi-tags-fill', 10);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (11, 'ข้อมูลค่าชิปปิ้ง', 'N', NULL, '/cost/shipping', 'bi bi-truck', 11);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (12, 'รายการสั่งซื้อ', 'N', NULL, '/orders', 'bi bi-receipt', 6);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (13, 'บันทึกรับเงินมัดจำ', 'N', NULL, '/deposit-balance', 'bi bi-cash-stack', 7);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (14, 'ปฏิทินกำหนดการ', 'N', NULL, '/schedule-calendar', 'bi bi-calendar-event', 1);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (15, 'รายงาน', 'N', NULL, '/reports', 'bi bi-file-earmark-bar-graph', 13);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (16, 'บันทึกค่าใช้จ่าย', 'N', NULL, '/cost/expense', 'bi bi-credit-card', 12);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (17, 'คำนวณราคาขาย', 'N', NULL, '/pricing-calculator', 'bi bi-calculator', 3);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (18, 'จัดการ Dashboard', 'N', NULL, '/dashboard/manage', 'bi bi-grid-1x2', 14);

-- t_payment_method: 3 rows
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (1, 'จ่ายเต็ม', 'A');
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (2, 'มัดจำ', 'A');
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (3, 'ชำระมัดจำแล้ว', 'D');

-- t_payment_type: 2 rows
INSERT INTO t_payment_type (id_pay_type, pt_name) VALUES (1, 'ของถึงไทย');
INSERT INTO t_payment_type (id_pay_type, pt_name) VALUES (2, 'กำหนดวัน');

-- t_order: 70 rows
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (1, '2026-05-01', 'PR-26-000001', 'FLOW50-20260521-231255-CUS-001', 1, NULL, NULL, 50.0, 0.0, 1290.0, 0.0, 0.0, 1340.0, 'FLOW50-20260521-231255 order 1');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (2, '2026-05-02', 'PR-26-000002', 'FLOW50-20260521-231255-CUS-002', 3, 1, NULL, 60.0, 0.0, 1780.0, 600.0, 0.0, 1840.0, 'FLOW50-20260521-231255 order 2');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (3, '2026-05-03', 'PR-26-000003', 'FLOW50-20260521-231255-CUS-003', 1, NULL, NULL, 70.0, 0.0, 4770.0, 0.0, 0.0, 4840.0, 'FLOW50-20260521-231255 order 3');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (4, '2026-05-04', 'PR-26-000004', 'FLOW50-20260521-231255-CUS-004', 3, 2, '2026-06-14', 50.0, 0.0, 5160.0, 2000.0, 0.0, 5210.0, 'FLOW50-20260521-231255 order 4');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (5, '2026-05-05', 'PR-26-000005', 'FLOW50-20260521-231255-CUS-005', 1, NULL, NULL, 60.0, 0.0, 890.0, 0.0, 0.0, 950.0, 'FLOW50-20260521-231255 order 5');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (6, '2026-05-06', 'PR-26-000006', 'FLOW50-20260521-231255-CUS-006', 3, 1, NULL, 70.0, 0.0, 3180.0, 1300.0, 0.0, 3250.0, 'FLOW50-20260521-231255 order 6');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (7, '2026-05-07', 'PR-26-000007', 'FLOW50-20260521-231255-CUS-007', 1, NULL, NULL, 50.0, 20.0, 3870.0, 0.0, 0.0, 3900.0, 'FLOW50-20260521-231255 order 7');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (8, '2026-05-08', 'PR-26-000008', 'FLOW50-20260521-231255-CUS-008', 3, 2, '2026-06-10', 60.0, 0.0, 3560.0, 1200.0, 0.0, 3620.0, 'FLOW50-20260521-231255 order 8');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (9, '2026-05-09', 'PR-26-000009', 'FLOW50-20260521-231255-CUS-009', 1, NULL, NULL, 70.0, 0.0, 1590.0, 0.0, 0.0, 1660.0, 'FLOW50-20260521-231255 order 9');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (10, '2026-05-10', 'PR-26-000010', 'FLOW50-20260521-231255-CUS-010', 3, 1, NULL, 50.0, 0.0, 2580.0, 1000.0, 0.0, 2630.0, 'FLOW50-20260521-231255 order 10');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (11, '2026-05-11', 'PR-26-000011', 'FLOW50-20260521-231255-CUS-011', 1, NULL, NULL, 60.0, 0.0, 2670.0, 0.0, 0.0, 2730.0, 'FLOW50-20260521-231255 order 11');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (12, '2026-05-12', 'PR-26-000012', 'FLOW50-20260521-231255-CUS-012', 3, 2, '2026-06-14', 70.0, 0.0, 6360.0, 2600.0, 0.0, 6430.0, 'FLOW50-20260521-231255 order 12');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (13, '2026-05-13', 'PR-26-000013', 'FLOW50-20260521-231255-CUS-013', 1, NULL, NULL, 50.0, 0.0, 1290.0, 0.0, 0.0, 1340.0, 'FLOW50-20260521-231255 order 13');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (14, '2026-05-14', 'PR-26-000014', 'FLOW50-20260521-231255-CUS-014', 3, 1, NULL, 60.0, 20.0, 1780.0, 600.0, 0.0, 1820.0, 'FLOW50-20260521-231255 order 14');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (15, '2026-05-15', 'PR-26-000015', 'FLOW50-20260521-231255-CUS-015', 1, NULL, NULL, 70.0, 0.0, 4770.0, 0.0, 0.0, 4840.0, 'FLOW50-20260521-231255 order 15');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (16, '2026-05-16', 'PR-26-000016', 'FLOW50-20260521-231255-CUS-016', 3, 2, '2026-06-10', 50.0, 0.0, 5160.0, 2000.0, 0.0, 5210.0, 'FLOW50-20260521-231255 order 16');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (17, '2026-05-17', 'PR-26-000017', 'FLOW50-20260521-231255-CUS-017', 1, NULL, NULL, 60.0, 0.0, 890.0, 0.0, 0.0, 950.0, 'FLOW50-20260521-231255 order 17');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (18, '2026-05-18', 'PR-26-000018', 'FLOW50-20260521-231255-CUS-018', 3, 1, NULL, 70.0, 0.0, 3180.0, 1300.0, 0.0, 3250.0, 'FLOW50-20260521-231255 order 18');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (19, '2026-05-19', 'PR-26-000019', 'FLOW50-20260521-231255-CUS-019', 1, NULL, NULL, 50.0, 0.0, 3870.0, 0.0, 0.0, 3920.0, 'FLOW50-20260521-231255 order 19');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (20, '2026-05-20', 'PR-26-000020', 'FLOW50-20260521-231255-CUS-020', 3, 2, '2026-06-14', 60.0, 0.0, 3560.0, 1200.0, 0.0, 3620.0, 'FLOW50-20260521-231255 order 20');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (21, '2026-05-21', 'PR-26-000021', 'FLOW50-20260521-231255-CUS-021', 1, NULL, NULL, 70.0, 20.0, 1590.0, 0.0, 0.0, 1640.0, 'FLOW50-20260521-231255 order 21');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (22, '2026-05-22', 'PR-26-000022', 'FLOW50-20260521-231255-CUS-022', 2, 1, NULL, 50.0, 0.0, 2580.0, 1000.0, 1630.0, 2630.0, 'FLOW50-20260521-231255 order 22');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (23, '2026-05-23', 'PR-26-000023', 'FLOW50-20260521-231255-CUS-023', 1, NULL, NULL, 60.0, 0.0, 2670.0, 0.0, 0.0, 2730.0, 'FLOW50-20260521-231255 order 23');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (24, '2026-05-24', 'PR-26-000024', 'FLOW50-20260521-231255-CUS-024', 2, 2, '2026-06-10', 70.0, 0.0, 6360.0, 2600.0, 3830.0, 6430.0, 'FLOW50-20260521-231255 order 24');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (25, '2026-05-25', 'PR-26-000025', 'FLOW50-20260521-231255-CUS-025', 1, NULL, NULL, 50.0, 0.0, 1290.0, 0.0, 0.0, 1340.0, 'FLOW50-20260521-231255 order 25');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (26, '2026-05-26', 'PR-26-000026', 'FLOW50-20260521-231255-CUS-026', 2, 1, NULL, 60.0, 0.0, 1780.0, 600.0, 1240.0, 1840.0, 'FLOW50-20260521-231255 order 26');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (27, '2026-05-27', 'PR-26-000027', 'FLOW50-20260521-231255-CUS-027', 1, NULL, NULL, 70.0, 0.0, 4770.0, 0.0, 0.0, 4840.0, 'FLOW50-20260521-231255 order 27');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (28, '2026-05-28', 'PR-26-000028', 'FLOW50-20260521-231255-CUS-028', 2, 2, '2026-06-14', 50.0, 20.0, 5160.0, 2000.0, 3190.0, 5190.0, 'FLOW50-20260521-231255 order 28');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (29, '2026-05-01', 'PR-26-000029', 'FLOW50-20260521-231255-CUS-029', 1, NULL, NULL, 60.0, 0.0, 890.0, 0.0, 0.0, 950.0, 'FLOW50-20260521-231255 order 29');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (30, '2026-05-02', 'PR-26-000030', 'FLOW50-20260521-231255-CUS-030', 2, 1, NULL, 70.0, 0.0, 3180.0, 1300.0, 1950.0, 3250.0, 'FLOW50-20260521-231255 order 30');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (31, '2026-05-03', 'PR-26-000031', 'FLOW50-20260521-231255-CUS-031', 1, NULL, NULL, 50.0, 0.0, 3870.0, 0.0, 0.0, 3920.0, 'FLOW50-20260521-231255 order 31');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (32, '2026-05-04', 'PR-26-000032', 'FLOW50-20260521-231255-CUS-032', 2, 2, '2026-06-10', 60.0, 0.0, 3560.0, 1200.0, 2420.0, 3620.0, 'FLOW50-20260521-231255 order 32');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (33, '2026-05-05', 'PR-26-000033', 'FLOW50-20260521-231255-CUS-033', 1, NULL, NULL, 70.0, 0.0, 1590.0, 0.0, 0.0, 1660.0, 'FLOW50-20260521-231255 order 33');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (34, '2026-05-06', 'PR-26-000034', 'FLOW50-20260521-231255-CUS-034', 2, 1, NULL, 50.0, 0.0, 2580.0, 1000.0, 1630.0, 2630.0, 'FLOW50-20260521-231255 order 34');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (35, '2026-05-07', 'PR-26-000035', 'FLOW50-20260521-231255-CUS-035', 1, NULL, NULL, 60.0, 20.0, 2670.0, 0.0, 0.0, 2710.0, 'FLOW50-20260521-231255 order 35');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (36, '2026-05-08', 'PR-26-000036', 'FLOW50-20260521-231255-CUS-036', 2, 2, '2026-06-14', 70.0, 0.0, 6360.0, 2600.0, 3830.0, 6430.0, 'FLOW50-20260521-231255 order 36');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (37, '2026-05-09', 'PR-26-000037', 'FLOW50-20260521-231255-CUS-037', 1, NULL, NULL, 50.0, 0.0, 1290.0, 0.0, 0.0, 1340.0, 'FLOW50-20260521-231255 order 37');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (38, '2026-05-10', 'PR-26-000038', 'FLOW50-20260521-231255-CUS-038', 2, 1, NULL, 60.0, 0.0, 1780.0, 600.0, 1240.0, 1840.0, 'FLOW50-20260521-231255 order 38');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (39, '2026-05-11', 'PR-26-000039', 'FLOW50-20260521-231255-CUS-039', 1, NULL, NULL, 70.0, 0.0, 4770.0, 0.0, 0.0, 4840.0, 'FLOW50-20260521-231255 order 39');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (40, '2026-05-12', 'PR-26-000040', 'FLOW50-20260521-231255-CUS-040', 2, 2, '2026-06-10', 50.0, 0.0, 5160.0, 2000.0, 3210.0, 5210.0, 'FLOW50-20260521-231255 order 40');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (41, '2026-05-13', 'PR-26-000041', 'FLOW50-20260521-231255-CUS-041', 1, NULL, NULL, 60.0, 0.0, 890.0, 0.0, 0.0, 950.0, 'FLOW50-20260521-231255 order 41');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (42, '2026-05-14', 'PR-26-000042', 'FLOW50-20260521-231255-CUS-042', 2, 1, NULL, 70.0, 20.0, 3180.0, 1300.0, 1930.0, 3230.0, 'FLOW50-20260521-231255 order 42');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (43, '2026-05-15', 'PR-26-000043', 'FLOW50-20260521-231255-CUS-043', 1, NULL, NULL, 50.0, 0.0, 3870.0, 0.0, 0.0, 3920.0, 'FLOW50-20260521-231255 order 43');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (44, '2026-05-16', 'PR-26-000044', 'FLOW50-20260521-231255-CUS-044', 2, 2, '2026-06-14', 60.0, 0.0, 3560.0, 1200.0, 2420.0, 3620.0, 'FLOW50-20260521-231255 order 44');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (45, '2026-05-17', 'PR-26-000045', 'FLOW50-20260521-231255-CUS-045', 1, NULL, NULL, 70.0, 0.0, 1590.0, 0.0, 0.0, 1660.0, 'FLOW50-20260521-231255 order 45');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (46, '2026-05-18', 'PR-26-000046', 'FLOW50-20260521-231255-CUS-046', 2, 1, NULL, 50.0, 0.0, 2580.0, 1000.0, 1630.0, 2630.0, 'FLOW50-20260521-231255 order 46');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (47, '2026-05-19', 'PR-26-000047', 'FLOW50-20260521-231255-CUS-047', 1, NULL, NULL, 60.0, 0.0, 2670.0, 0.0, 0.0, 2730.0, 'FLOW50-20260521-231255 order 47');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (48, '2026-05-20', 'PR-26-000048', 'FLOW50-20260521-231255-CUS-048', 2, 2, '2026-06-10', 70.0, 0.0, 6360.0, 2600.0, 3830.0, 6430.0, 'FLOW50-20260521-231255 order 48');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (49, '2026-05-21', 'PR-26-000049', 'FLOW50-20260521-231255-CUS-049', 1, NULL, NULL, 50.0, 20.0, 1290.0, 0.0, 0.0, 1320.0, 'FLOW50-20260521-231255 order 49');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (50, '2026-05-22', 'PR-26-000050', 'FLOW50-20260521-231255-CUS-050', 2, 1, NULL, 60.0, 0.0, 1780.0, 600.0, 1240.0, 1840.0, 'FLOW50-20260521-231255 order 50');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (51, '2026-07-01', 'PR-26-000051', 'STATUS20-20260522-002659-CUS-001', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 1');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (52, '2026-07-02', 'PR-26-000052', 'STATUS20-20260522-002659-CUS-002', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 2');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (53, '2026-07-03', 'PR-26-000053', 'STATUS20-20260522-002659-CUS-003', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 3');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (54, '2026-07-04', 'PR-26-000054', 'STATUS20-20260522-002659-CUS-004', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 4');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (55, '2026-07-05', 'PR-26-000055', 'STATUS20-20260522-002659-CUS-005', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 5');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (56, '2026-07-06', 'PR-26-000056', 'STATUS20-20260522-002659-CUS-006', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 6');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (57, '2026-07-07', 'PR-26-000057', 'STATUS20-20260522-002659-CUS-007', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 7');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (58, '2026-07-08', 'PR-26-000058', 'STATUS20-20260522-002659-CUS-008', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 8');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (59, '2026-07-09', 'PR-26-000059', 'STATUS20-20260522-002659-CUS-009', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 9');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (60, '2026-07-10', 'PR-26-000060', 'STATUS20-20260522-002659-CUS-010', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 10');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (61, '2026-07-11', 'PR-26-000061', 'STATUS20-20260522-002659-CUS-011', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 11');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (62, '2026-07-12', 'PR-26-000062', 'STATUS20-20260522-002659-CUS-012', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 12');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (63, '2026-07-13', 'PR-26-000063', 'STATUS20-20260522-002659-CUS-013', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 13');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (64, '2026-07-14', 'PR-26-000064', 'STATUS20-20260522-002659-CUS-014', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 14');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (65, '2026-07-15', 'PR-26-000065', 'STATUS20-20260522-002659-CUS-015', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 15');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (66, '2026-07-16', 'PR-26-000066', 'STATUS20-20260522-002659-CUS-016', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 16');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (67, '2026-07-17', 'PR-26-000067', 'STATUS20-20260522-002659-CUS-017', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 17');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (68, '2026-07-18', 'PR-26-000068', 'STATUS20-20260522-002659-CUS-018', 1, NULL, NULL, 50.0, 0.0, 2970.0, 0.0, 0.0, 3020.0, 'STATUS20-20260522-002659 status change 18');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (69, '2026-07-19', 'PR-26-000069', 'STATUS20-20260522-002659-CUS-019', 1, NULL, NULL, 50.0, 0.0, 990.0, 0.0, 0.0, 1040.0, 'STATUS20-20260522-002659 status change 19');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (70, '2026-07-20', 'PR-26-000070', 'STATUS20-20260522-002659-CUS-020', 1, NULL, NULL, 50.0, 0.0, 1980.0, 0.0, 0.0, 2030.0, 'STATUS20-20260522-002659 status change 20');

-- t_order_status: 5 rows
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (1, 'รอกดของ', 'warning');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (2, 'กดของแล้ว รอเข้าโกดัง', 'info');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (3, 'รอของถึงร้าน', 'orange');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (4, 'ถึงร้านแล้วรอส่ง', 'danger');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (5, 'ส่งของสำเร็จ', 'success');

-- t_order_detail: 70 rows
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (1, 1, 4, 1, 1290.0, 500.0, 790.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (2, 2, 5, 2, 1780.0, 600.0, 1180.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (3, 3, 6, 3, 4770.0, 1950.0, 2820.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (4, 4, 4, 4, 5160.0, 2000.0, 3160.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (5, 5, 5, 1, 890.0, 300.0, 590.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (6, 6, 6, 2, 3180.0, 1300.0, 1880.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (7, 7, 4, 3, 3870.0, 1500.0, 2370.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (8, 8, 5, 4, 3560.0, 1200.0, 2360.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (9, 9, 6, 1, 1590.0, 650.0, 940.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (10, 10, 4, 2, 2580.0, 1000.0, 1580.0, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (11, 11, 5, 3, 2670.0, 900.0, 1770.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (12, 12, 6, 4, 6360.0, 2600.0, 3760.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (13, 13, 4, 1, 1290.0, 500.0, 790.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (14, 14, 5, 2, 1780.0, 600.0, 1180.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (15, 15, 6, 3, 4770.0, 1950.0, 2820.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (16, 16, 4, 4, 5160.0, 2000.0, 3160.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (17, 17, 5, 1, 890.0, 300.0, 590.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (18, 18, 6, 2, 3180.0, 1300.0, 1880.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (19, 19, 4, 3, 3870.0, 1500.0, 2370.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (20, 20, 5, 4, 3560.0, 1200.0, 2360.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (21, 21, 6, 1, 1590.0, 650.0, 940.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (22, 22, 4, 2, 2580.0, 1000.0, 1580.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (23, 23, 5, 3, 2670.0, 900.0, 1770.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (24, 24, 6, 4, 6360.0, 2600.0, 3760.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (25, 25, 4, 1, 1290.0, 500.0, 790.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (26, 26, 5, 2, 1780.0, 600.0, 1180.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (27, 27, 6, 3, 4770.0, 1950.0, 2820.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (28, 28, 4, 4, 5160.0, 2000.0, 3160.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (29, 29, 5, 1, 890.0, 300.0, 590.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (30, 30, 6, 2, 3180.0, 1300.0, 1880.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (31, 31, 4, 3, 3870.0, 1500.0, 2370.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (32, 32, 5, 4, 3560.0, 1200.0, 2360.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (33, 33, 6, 1, 1590.0, 650.0, 940.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (34, 34, 4, 2, 2580.0, 1000.0, 1580.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (35, 35, 5, 3, 2670.0, 900.0, 1770.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (36, 36, 6, 4, 6360.0, 2600.0, 3760.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (37, 37, 4, 1, 1290.0, 500.0, 790.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (38, 38, 5, 2, 1780.0, 600.0, 1180.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (39, 39, 6, 3, 4770.0, 1950.0, 2820.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (40, 40, 4, 4, 5160.0, 2000.0, 3160.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (41, 41, 5, 1, 890.0, 300.0, 590.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (42, 42, 6, 2, 3180.0, 1300.0, 1880.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (43, 43, 4, 3, 3870.0, 1500.0, 2370.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (44, 44, 5, 4, 3560.0, 1200.0, 2360.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (45, 45, 6, 1, 1590.0, 650.0, 940.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (46, 46, 4, 2, 2580.0, 1000.0, 1580.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (47, 47, 5, 3, 2670.0, 900.0, 1770.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (48, 48, 6, 4, 6360.0, 2600.0, 3760.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (49, 49, 4, 1, 1290.0, 500.0, 790.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (50, 50, 5, 2, 1780.0, 600.0, 1180.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (51, 51, 7, 1, 990.0, 350.0, 640.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (52, 52, 7, 2, 1980.0, 700.0, 1280.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (53, 53, 7, 3, 2970.0, 1050.0, 1920.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (54, 54, 7, 1, 990.0, 350.0, 640.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (55, 55, 7, 2, 1980.0, 700.0, 1280.0, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (56, 56, 7, 3, 2970.0, 1050.0, 1920.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (57, 57, 7, 1, 990.0, 350.0, 640.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (58, 58, 7, 2, 1980.0, 700.0, 1280.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (59, 59, 7, 3, 2970.0, 1050.0, 1920.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (60, 60, 7, 1, 990.0, 350.0, 640.0, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (61, 61, 7, 2, 1980.0, 700.0, 1280.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (62, 62, 7, 3, 2970.0, 1050.0, 1920.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (63, 63, 7, 1, 990.0, 350.0, 640.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (64, 64, 7, 2, 1980.0, 700.0, 1280.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (65, 65, 7, 3, 2970.0, 1050.0, 1920.0, 4);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (66, 66, 7, 1, 990.0, 350.0, 640.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (67, 67, 7, 2, 1980.0, 700.0, 1280.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (68, 68, 7, 3, 2970.0, 1050.0, 1920.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (69, 69, 7, 1, 990.0, 350.0, 640.0, 5);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (70, 70, 7, 2, 1980.0, 700.0, 1280.0, 5);

-- t_settings: 6 rows
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (1, 'theme_mode', 'dark');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (2, 'schedule_show_completed', 'true');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (3, 'dashboard_chart_series', 'amount,receivedPaid,pledgePaid,pressCost,shippingCost');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (4, 'dashboard_chart_granularity', 'day');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (5, 'order_show_closed_products', 'true');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (6, 'dashboard_widgets', '[{"id":"widget-1779535286404","title":"ศิลปินยอดนิยม","type":"donut","dataset":"artistSalesShare","width":"25","tone":"primary","order":1}]');

-- t_log_version was not present in the MySQL source; keep footer version available.
INSERT INTO t_log_version (id_log_version, lv_version, lv_date) VALUES (1, '1.0.0', '2026-05-21');

SELECT setval(pg_get_serial_sequence('t_group', 'id_group'), COALESCE((SELECT MAX(id_group) FROM t_group), 1));
SELECT setval(pg_get_serial_sequence('t_artist', 'id_art'), COALESCE((SELECT MAX(id_art) FROM t_artist), 1));
SELECT setval(pg_get_serial_sequence('t_type', 'id_type'), COALESCE((SELECT MAX(id_type) FROM t_type), 1));
SELECT setval(pg_get_serial_sequence('t_website', 'id_web'), COALESCE((SELECT MAX(id_web) FROM t_website), 1));
SELECT setval(pg_get_serial_sequence('t_version', 'id_ver'), COALESCE((SELECT MAX(id_ver) FROM t_version), 1));
SELECT setval(pg_get_serial_sequence('t_product', 'id_product'), COALESCE((SELECT MAX(id_product) FROM t_product), 1));
SELECT setval(pg_get_serial_sequence('t_cover', 'id_cover'), COALESCE((SELECT MAX(id_cover) FROM t_cover), 1));
SELECT setval(pg_get_serial_sequence('t_product_web', 'id_pro_web'), COALESCE((SELECT MAX(id_pro_web) FROM t_product_web), 1));
SELECT setval(pg_get_serial_sequence('t_cost', 'id_cost'), COALESCE((SELECT MAX(id_cost) FROM t_cost), 1));
SELECT setval(pg_get_serial_sequence('t_cost_detail', 'id_cost_detail'), COALESCE((SELECT MAX(id_cost_detail) FROM t_cost_detail), 1));
SELECT setval(pg_get_serial_sequence('t_income', 'id_income'), COALESCE((SELECT MAX(id_income) FROM t_income), 1));
SELECT setval(pg_get_serial_sequence('t_lot', 'id_lot'), COALESCE((SELECT MAX(id_lot) FROM t_lot), 1));
SELECT setval(pg_get_serial_sequence('t_lot_detail', 'id_lot_detail'), COALESCE((SELECT MAX(id_lot_detail) FROM t_lot_detail), 1));
SELECT setval(pg_get_serial_sequence('t_menu', 'id_menu'), COALESCE((SELECT MAX(id_menu) FROM t_menu), 1));
SELECT setval(pg_get_serial_sequence('t_order', 'id_order'), COALESCE((SELECT MAX(id_order) FROM t_order), 1));
SELECT setval(pg_get_serial_sequence('t_order_detail', 'id_order_detail'), COALESCE((SELECT MAX(id_order_detail) FROM t_order_detail), 1));
SELECT setval(pg_get_serial_sequence('t_sale', 'id_sale'), COALESCE((SELECT MAX(id_sale) FROM t_sale), 1));
SELECT setval(pg_get_serial_sequence('t_settings', 'id_setting'), COALESCE((SELECT MAX(id_setting) FROM t_settings), 1));
SELECT setval(pg_get_serial_sequence('t_log_version', 'id_log_version'), COALESCE((SELECT MAX(id_log_version) FROM t_log_version), 1));
SELECT setval(pg_get_serial_sequence('t_user', 'id_user'), COALESCE((SELECT MAX(id_user) FROM t_user), 1));
COMMIT;

