-- PostgreSQL schema for Sriundee Shop.
-- Run this on a clean PostgreSQL database before starting the Spring Boot app.

DROP VIEW IF EXISTS q_cost_detail, q_report_money_income, q_report_money_cost, q_product_web, q_product,
    q_order_detail, q_order, q_income, q_group_website, q_end_date, q_customer_name, q_cover, q_cost,
    q_artist, q_send_date CASCADE;

DROP TABLE IF EXISTS t_cost_detail, t_lot_detail, t_order_detail, t_income, t_cost, t_lot, t_order,
    t_cover, t_product_web, t_product, t_artist, t_group, t_menu, t_order_status, t_payment_method,
    t_payment_type, t_product_status, t_sale, t_settings, t_type, t_type_cost, t_type_income,
    t_version, t_website, t_log_version, t_user CASCADE;

CREATE TABLE t_group (
    id_group integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g_name varchar(255),
    g_delete varchar(255)
);

CREATE TABLE t_artist (
    id_art integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_name varchar(255),
    id_group integer,
    a_logo varchar(255),
    a_delete varchar(255)
);

CREATE TABLE t_type (
    id_type integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_name varchar(255),
    t_delete varchar(255)
);

CREATE TABLE t_website (
    id_web integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    w_name varchar(255),
    w_delete varchar(255)
);

CREATE TABLE t_version (
    id_ver integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    v_name varchar(255),
    v_delete varchar(255)
);

CREATE TABLE t_product_status (
    id_pro_status integer PRIMARY KEY,
    ps_name varchar(255)
);

CREATE TABLE t_product (
    id_product integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_name varchar(255),
    id_type integer,
    id_art integer,
    p_end_date date,
    p_send_date date,
    id_pro_status integer,
    p_delete varchar(255),
    p_pic varchar(255),
    p_last_pay_date date
);

CREATE TABLE t_cover (
    id_cover integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    id_web integer,
    id_ver integer,
    c_name varchar(255),
    c_price_total varchar(255),
    c_price_pledge varchar(255),
    c_price_balance varchar(255),
    c_delete varchar(255)
);

CREATE TABLE t_product_web (
    id_pro_web integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    id_web integer
);

CREATE TABLE t_type_cost (
    id_type_cost integer PRIMARY KEY,
    tc_name varchar(255)
);

CREATE TABLE t_cost (
    id_cost integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_create_date varchar(255),
    id_type_cost integer,
    c_price varchar(255),
    c_note varchar(255),
    c_delete varchar(255)
);

CREATE TABLE t_cost_detail (
    id_cost_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cost integer,
    id_order_detail integer
);

CREATE TABLE t_type_income (
    id_type_income integer PRIMARY KEY,
    ti_name varchar(255)
);

CREATE TABLE t_income (
    id_income integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_create_date varchar(255),
    c_customer_name varchar(255),
    id_type_income integer,
    c_price varchar(255),
    c_note varchar(255),
    c_delete varchar(255),
    id_order integer,
    id_sale integer
);

CREATE TABLE t_lot (
    id_lot integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    l_lot_number varchar(255),
    l_create_date varchar(255),
    l_start_date varchar(255),
    l_end_date varchar(255),
    l_arrive_date varchar(255),
    l_delete varchar(255)
);

CREATE TABLE t_lot_detail (
    id_lot_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lot integer,
    id_order_detail integer
);

CREATE TABLE t_menu (
    id_menu integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m_name varchar(255),
    m_parent varchar(255),
    m_id_menu integer,
    m_url varchar(255),
    m_icon varchar(255),
    m_order integer
);

CREATE TABLE t_payment_method (
    id_pay_method integer PRIMARY KEY,
    pm_name varchar(255),
    pm_delete varchar(255)
);

CREATE TABLE t_payment_type (
    id_pay_type integer PRIMARY KEY,
    pt_name varchar(255)
);

CREATE TABLE t_order (
    id_order integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    o_order_date date,
    o_order_code varchar(255),
    o_customer_name varchar(255),
    id_pay_method integer,
    id_pay_type integer,
    o_last_pay_date date,
    o_send_cost double precision,
    o_discount double precision,
    o_price_total double precision,
    o_price_pledge double precision,
    o_price_balance double precision,
    o_net double precision,
    o_remark varchar(255)
);

CREATE TABLE t_order_status (
    id_order_status integer PRIMARY KEY,
    os_name varchar(255),
    os_color varchar(255)
);

CREATE TABLE t_order_detail (
    id_order_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_order integer,
    id_cover integer,
    od_qty integer,
    od_price_total double precision,
    od_price_pledge double precision,
    od_price_balance double precision,
    id_order_status integer,
    id_user integer
);

CREATE UNIQUE INDEX uq_t_order_order_code ON t_order (o_order_code);

CREATE TABLE t_sale (
    id_sale integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_customer_name varchar(255),
    s_product_name varchar(255),
    id_type integer,
    id_art integer,
    s_price varchar(255),
    s_num varchar(255),
    s_shiping varchar(255),
    s_net varchar(255),
    s_note varchar(255),
    id_pre_status varchar(255),
    s_delete varchar(255),
    s_pending varchar(255),
    s_send_date varchar(255)
);

CREATE TABLE t_settings (
    id_setting integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_key varchar(255),
    s_value text,
    id_user integer
);

CREATE TABLE t_log_version (
    id_log_version integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lv_version varchar(255),
    lv_date varchar(255)
);

CREATE TABLE t_user (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    u_username varchar(255),
    u_delete varchar(255)
);

CREATE INDEX idx_t_settings_key_user ON t_settings (s_key, id_user);
CREATE INDEX idx_t_user_username ON t_user (LOWER(u_username));

INSERT INTO t_group VALUES
    (1, 'SM', 'A'), (2, 'YG', 'A'), (3, 'JYP', 'A'), (4, 'HYPE', 'A'), (5, 'อื่น ๆ', 'A');

INSERT INTO t_menu VALUES
    (2, 'ข้อมูลพื้นฐาน', 'Y', NULL, NULL, 'bi bi-stack', 2),
    (3, 'ข้อมูลศิลปิน', NULL, 2, '/artist', NULL, 1),
    (4, 'ข้อมูลประเภทสินค้า', NULL, 2, '/type', NULL, 2),
    (5, 'ข้อมูลเว็บไซต์', NULL, 2, '/website', NULL, 3),
    (6, 'ข้อมูลสินค้า', 'N', NULL, '/product', 'bi bi-book-half', 3),
    (7, 'บันทึกออร์เดอร์', 'N', NULL, '/order', 'bi bi-basket', 4),
    (8, 'อัปเดทสถานะ', 'N', NULL, '/change', 'bi bi-check-circle-fill', 7),
    (9, 'ข้อมูลการกดของ', 'N', NULL, '/check_status_2', 'bi bi-clipboard-check', 8),
    (10, 'ข้อมูล LOT', 'N', NULL, '/lot', 'bi bi-tags-fill', 9),
    (11, 'ข้อมูลค่าชิปปิ้ง', 'N', NULL, '/cost/shipping', 'bi bi-truck', 10),
    (12, 'รายการสั่งซื้อ', 'N', NULL, '/orders', 'bi bi-receipt', 5),
    (13, 'บันทึกรับเงินมัดจำ', 'N', NULL, '/deposit-balance', 'bi bi-cash-stack', 6),
    (14, 'ปฏิทินกำหนดการ', 'N', NULL, '/schedule-calendar', 'bi bi-calendar-event', 1),
    (15, 'รายงาน', 'N', NULL, '/reports', 'bi bi-file-earmark-bar-graph', 11),
    (16, 'บันทึกค่าใช้จ่าย', 'N', NULL, '/cost/expense', 'bi bi-credit-card', 12),
    (17, 'คำนวณราคาขาย', 'N', NULL, '/pricing-calculator', 'bi bi-calculator', 13),
    (18, 'จัดการ Dashboard', 'N', NULL, '/dashboard/manage', 'bi bi-grid-1x2', 14);

INSERT INTO t_order_status VALUES
    (1, 'รอกดของ', 'warning'),
    (2, 'กดของแล้ว รอเข้าโกดัง', 'info'),
    (3, 'รอของถึงร้าน', 'orange'),
    (4, 'ถึงร้านแล้วรอส่ง', 'danger'),
    (5, 'ส่งของสำเร็จ', 'success');

INSERT INTO t_payment_method VALUES
    (1, 'จ่ายเต็ม', 'A'),
    (2, 'มัดจำ', 'A'),
    (3, 'ชำระมัดจำแล้ว', 'D');

INSERT INTO t_payment_type VALUES (1, 'ของถึงไทย'), (2, 'กำหนดวัน');
INSERT INTO t_product_status VALUES (1, 'เปิดพรี'), (2, 'ปิดพรี');

INSERT INTO t_settings (id_setting, s_key, s_value) VALUES
    (1, 'theme_mode', 'dark'),
    (2, 'schedule_show_completed', 'true'),
    (3, 'dashboard_chart_series', 'amount,receivedPaid,pledgePaid,pressCost,shippingCost'),
    (4, 'dashboard_chart_granularity', 'day'),
    (5, 'order_show_closed_products', 'false'),
    (6, 'dashboard_widgets', '[]');

INSERT INTO t_type_cost VALUES
    (1, 'ค่ากดของ'),
    (2, 'ค่าชิปปิ้ง'),
    (3, 'ค่าสั่งกล่อง'),
    (4, 'ค่าสั่งทำของแถม'),
    (5, 'ค่าส่งไปรษณีย์'),
    (99, 'อื่น ๆ');

INSERT INTO t_type_income VALUES
    (1, 'ค่าของ ( จ่ายเต็ม )'),
    (2, 'ค่าของ ( มัดจำ )'),
    (3, 'ยอดมัดจำที่เหลือ'),
    (4, 'ของพร้อมส่ง');

INSERT INTO t_log_version VALUES (1, '1.0.0', '2026-05-21');
INSERT INTO t_log_version VALUES (2, '1.0.1', '2026-05-25');

SELECT setval(pg_get_serial_sequence('t_group', 'id_group'), COALESCE((SELECT MAX(id_group) FROM t_group), 1));
SELECT setval(pg_get_serial_sequence('t_menu', 'id_menu'), COALESCE((SELECT MAX(id_menu) FROM t_menu), 1));
SELECT setval(pg_get_serial_sequence('t_settings', 'id_setting'), COALESCE((SELECT MAX(id_setting) FROM t_settings), 1));
SELECT setval(pg_get_serial_sequence('t_log_version', 'id_log_version'), COALESCE((SELECT MAX(id_log_version) FROM t_log_version), 1));

CREATE VIEW q_artist AS
SELECT a.id_art, a.a_name, a.id_group, g.g_name, a.a_logo, a.a_delete
FROM t_artist a
JOIN t_group g ON g.id_group = a.id_group;

CREATE VIEW q_cost AS
SELECT c.id_cost, c.c_create_date, c.id_type_cost, tc.tc_name, c.c_price, c.c_note, c.c_delete
FROM t_cost c
JOIN t_type_cost tc ON tc.id_type_cost = c.id_type_cost;

CREATE VIEW q_cover AS
SELECT c.id_cover, c.id_pro, p.p_name, p.id_type, t.t_name, c.id_web, w.w_name, c.id_ver, v.v_name,
       c.c_name, c.c_price_total, c.c_price_pledge, c.c_price_balance, c.c_delete
FROM t_cover c
JOIN t_product p ON p.id_product = c.id_pro
JOIN t_website w ON w.id_web = c.id_web
JOIN t_version v ON v.id_ver = c.id_ver
JOIN t_type t ON t.id_type = p.id_type;

CREATE VIEW q_customer_name AS
SELECT o_customer_name
FROM t_order
GROUP BY o_customer_name;

CREATE VIEW q_group_website AS
SELECT c.id_web, w.w_name, c.id_pro, c.c_delete
FROM t_cover c
JOIN t_website w ON w.id_web = c.id_web
GROUP BY c.id_web, w.w_name, c.id_pro, c.c_delete;

CREATE VIEW q_income AS
SELECT i.id_income, i.c_create_date, i.c_customer_name, i.id_type_income, ti.ti_name,
       i.c_price, i.c_note, i.c_delete, i.id_order
FROM t_income i
JOIN t_type_income ti ON ti.id_type_income = i.id_type_income;

CREATE VIEW q_order AS
SELECT o.id_order, o.o_order_date, o.o_order_code, o.o_customer_name, o.id_pay_method,
       pm.pm_name, o.o_send_cost, o.o_discount, o.o_price_total, o.id_pay_type, pt.pt_name,
       o.o_price_pledge, o.o_price_balance, o.o_last_pay_date, o.o_net, o.o_remark
FROM t_order o
JOIN t_payment_method pm ON pm.id_pay_method = o.id_pay_method
LEFT JOIN t_payment_type pt ON pt.id_pay_type = o.id_pay_type;

CREATE VIEW q_order_detail AS
SELECT od.id_order_detail, od.id_order, o.o_customer_name, c.id_pro, p.p_name, p.id_type, t.t_name,
       p.id_art, a.a_name, c.id_web, w.w_name, c.id_ver, v.v_name, od.id_cover, c.c_name,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_total, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_total,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_pledge, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_pledge,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_balance, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_balance,
       od.od_qty,
       TO_CHAR(COALESCE(od.od_price_total, 0), 'FM999G999G990') AS od_price_total,
       TO_CHAR(COALESCE(od.od_price_pledge, 0), 'FM999G999G990') AS od_price_pledge,
       TO_CHAR(COALESCE(od.od_price_balance, 0), 'FM999G999G990') AS od_price_balance,
       od.id_order_status, os.os_name, od.id_user
FROM t_order_detail od
JOIN t_cover c ON c.id_cover = od.id_cover
JOIN t_product p ON p.id_product = c.id_pro
JOIN t_website w ON w.id_web = c.id_web
JOIN t_version v ON v.id_ver = c.id_ver
JOIN t_type t ON t.id_type = p.id_type
JOIN t_artist a ON a.id_art = p.id_art
JOIN t_order_status os ON os.id_order_status = od.id_order_status
LEFT JOIN t_order o ON o.id_order = od.id_order;

CREATE VIEW q_cost_detail AS
SELECT cd.id_cost_detail, qc.id_cost, qc.c_create_date, qc.id_type_cost, qc.tc_name, qc.c_price,
       qc.c_note, qc.c_delete, qod.*
FROM t_cost_detail cd
JOIN q_cost qc ON qc.id_cost = cd.id_cost
JOIN q_order_detail qod ON qod.id_order_detail = cd.id_order_detail;

CREATE VIEW q_product AS
SELECT p.id_product, p.p_name, p.id_type, t.t_name, p.id_art, a.a_name, a.a_logo,
       TO_CHAR(p.p_end_date, 'DD/MM/YYYY') AS p_end_date,
       TO_CHAR(p.p_send_date, 'DD/MM/YYYY') AS p_send_date,
       p.id_pro_status, ps.ps_name, p.p_delete, p.p_pic
FROM t_product p
JOIN t_type t ON t.id_type = p.id_type
JOIN t_artist a ON a.id_art = p.id_art
JOIN t_product_status ps ON ps.id_pro_status = p.id_pro_status;

CREATE VIEW q_product_web AS
SELECT pw.id_pro_web, pw.id_pro, p.p_name, pw.id_web, w.w_name
FROM t_product_web pw
JOIN t_product p ON p.id_product = pw.id_pro
JOIN t_website w ON w.id_web = pw.id_web;

CREATE VIEW q_report_money_cost AS
SELECT c.id_cost AS id_r, c.c_create_date AS r_date, tc.tc_name AS r_name, c.c_price AS r_price,
       c.c_note AS r_note, c.c_delete AS r_delete, 'C' AS r_tpye
FROM t_cost c
JOIN t_type_cost tc ON tc.id_type_cost = c.id_type_cost;

CREATE VIEW q_report_money_income AS
SELECT i.id_income AS id_r, i.c_create_date AS r_date, ti.ti_name AS r_name, i.c_price AS r_price,
       i.c_note AS r_note, i.c_delete AS r_delete, i.id_order, 'I' AS r_tpye
FROM t_income i
JOIN t_type_income ti ON ti.id_type_income = i.id_type_income;

CREATE VIEW q_end_date AS
SELECT TO_CHAR(p_end_date, 'DD/MM/YYYY') AS p_end_date,
       EXTRACT(DAY FROM p_end_date)::integer AS p_end_date_day,
       EXTRACT(MONTH FROM p_end_date)::integer AS p_end_date_month,
       EXTRACT(YEAR FROM p_end_date)::integer AS p_end_date_year,
       id_pro_status, p_delete
FROM t_product;

CREATE VIEW q_send_date AS
SELECT TO_CHAR(p_send_date, 'DD/MM/YYYY') AS p_send_date,
       EXTRACT(DAY FROM p_send_date)::integer AS p_send_date_day,
       EXTRACT(MONTH FROM p_send_date)::integer AS p_send_date_month,
       EXTRACT(YEAR FROM p_send_date)::integer AS p_send_date_year,
       id_pro_status, p_delete
FROM t_product;
