-- PostgreSQL production schema and data converted from db_sriundee_shop_prod.sql.
-- Source: MySQL/Navicat dump.
-- Run on a clean PostgreSQL database, or be aware that this script truncates application tables.

-- PostgreSQL schema for Sriundee Shop.
-- Run this on a clean PostgreSQL database before starting the Spring Boot app.

DROP VIEW IF EXISTS q_cost_detail, q_report_money_income, q_report_money_cost, q_product_web, q_product,
    q_order_detail, q_order, q_income, q_group_website, q_end_date, q_customer_name, q_cover, q_cost,
    q_artist, q_send_date CASCADE;

DROP TABLE IF EXISTS t_cost_detail, t_lot_detail, t_order_detail, t_income, t_cost, t_lot, t_order,
    t_cover, t_product_web, t_product, t_artist, t_group, t_menu, t_order_status, t_payment_method,
    t_payment_type, t_product_status, t_sale, t_settings, t_type, t_type_cost, t_type_income,
    t_version, t_website, t_log_version, t_user CASCADE;

CREATE TABLE t_group (
    id_group integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g_name varchar(255),
    g_delete varchar(255)
);

CREATE TABLE t_artist (
    id_art integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_name varchar(255),
    id_group integer,
    a_logo varchar(255),
    a_delete varchar(255)
);

CREATE TABLE t_type (
    id_type integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_name varchar(255),
    t_delete varchar(255)
);

CREATE TABLE t_website (
    id_web integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    w_name varchar(255),
    w_delete varchar(255)
);

CREATE TABLE t_version (
    id_ver integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    v_name varchar(255),
    v_delete varchar(255)
);

CREATE TABLE t_product_status (
    id_pro_status integer PRIMARY KEY,
    ps_name varchar(255)
);

CREATE TABLE t_product (
    id_product integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_name varchar(255),
    id_type integer,
    id_art integer,
    p_end_date date,
    p_send_date date,
    id_pro_status integer,
    p_delete varchar(255),
    p_pic varchar(255),
    p_last_pay_date date
);

CREATE TABLE t_cover (
    id_cover integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    id_web integer,
    id_ver integer,
    c_name varchar(255),
    c_price_total varchar(255),
    c_price_pledge varchar(255),
    c_price_balance varchar(255),
    c_delete varchar(255)
);

CREATE TABLE t_product_web (
    id_pro_web integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pro integer,
    id_web integer
);

CREATE TABLE t_type_cost (
    id_type_cost integer PRIMARY KEY,
    tc_name varchar(255)
);

CREATE TABLE t_cost (
    id_cost integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_create_date varchar(255),
    id_type_cost integer,
    c_price varchar(255),
    c_note varchar(255),
    c_delete varchar(255)
);

CREATE TABLE t_cost_detail (
    id_cost_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cost integer,
    id_order_detail integer
);

CREATE TABLE t_type_income (
    id_type_income integer PRIMARY KEY,
    ti_name varchar(255)
);

CREATE TABLE t_income (
    id_income integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_create_date varchar(255),
    c_customer_name varchar(255),
    id_type_income integer,
    c_price varchar(255),
    c_note varchar(255),
    c_delete varchar(255),
    id_order integer,
    id_sale integer
);

CREATE TABLE t_lot (
    id_lot integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    l_lot_number varchar(255),
    l_create_date varchar(255),
    l_start_date varchar(255),
    l_end_date varchar(255),
    l_arrive_date varchar(255),
    l_delete varchar(255)
);

CREATE TABLE t_lot_detail (
    id_lot_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lot integer,
    id_order_detail integer
);

CREATE TABLE t_menu (
    id_menu integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m_name varchar(255),
    m_parent varchar(255),
    m_id_menu integer,
    m_url varchar(255),
    m_icon varchar(255),
    m_order integer
);

CREATE TABLE t_payment_method (
    id_pay_method integer PRIMARY KEY,
    pm_name varchar(255),
    pm_delete varchar(255)
);

CREATE TABLE t_payment_type (
    id_pay_type integer PRIMARY KEY,
    pt_name varchar(255)
);

CREATE TABLE t_order (
    id_order integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    o_order_date date,
    o_order_code varchar(255),
    o_customer_name varchar(255),
    id_pay_method integer,
    id_pay_type integer,
    o_last_pay_date date,
    o_send_cost double precision,
    o_discount double precision,
    o_price_total double precision,
    o_price_pledge double precision,
    o_price_balance double precision,
    o_net double precision,
    o_remark varchar(255)
);

CREATE TABLE t_order_status (
    id_order_status integer PRIMARY KEY,
    os_name varchar(255),
    os_color varchar(255)
);

CREATE TABLE t_order_detail (
    id_order_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_order integer,
    id_cover integer,
    od_qty integer,
    od_price_total double precision,
    od_price_pledge double precision,
    od_price_balance double precision,
    id_order_status integer
);

CREATE TABLE t_sale (
    id_sale integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_customer_name varchar(255),
    s_product_name varchar(255),
    id_type integer,
    id_art integer,
    s_price varchar(255),
    s_num varchar(255),
    s_shiping varchar(255),
    s_net varchar(255),
    s_note varchar(255),
    id_pre_status varchar(255),
    s_delete varchar(255),
    s_pending varchar(255),
    s_send_date varchar(255)
);

CREATE TABLE t_settings (
    id_setting integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_key varchar(255),
    s_value text,
    id_user integer
);

CREATE TABLE t_log_version (
    id_log_version integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lv_version varchar(255),
    lv_date varchar(255)
);

CREATE TABLE t_user (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    u_username varchar(255),
    u_delete varchar(255)
);

CREATE INDEX idx_t_settings_key_user ON t_settings (s_key, id_user);
CREATE INDEX idx_t_user_username ON t_user (LOWER(u_username));

INSERT INTO t_group VALUES
    (1, 'SM', 'A'), (2, 'YG', 'A'), (3, 'JYP', 'A'), (4, 'HYPE', 'A'), (5, 'อื่น ๆ', 'A');

INSERT INTO t_menu VALUES
    (2, 'ข้อมูลพื้นฐาน', 'Y', NULL, NULL, 'bi bi-stack', 2),
    (3, 'ข้อมูลศิลปิน', NULL, 2, '/artist', NULL, 1),
    (4, 'ข้อมูลประเภทสินค้า', NULL, 2, '/type', NULL, 2),
    (5, 'ข้อมูลเว็บไซต์', NULL, 2, '/website', NULL, 3),
    (6, 'ข้อมูลสินค้า', 'N', NULL, '/product', 'bi bi-book-half', 3),
    (7, 'บันทึกออร์เดอร์', 'N', NULL, '/order', 'bi bi-basket', 4),
    (8, 'อัปเดทสถานะ', 'N', NULL, '/change', 'bi bi-check-circle-fill', 7),
    (9, 'ข้อมูลการกดของ', 'N', NULL, '/check_status_2', 'bi bi-clipboard-check', 8),
    (10, 'ข้อมูล LOT', 'N', NULL, '/lot', 'bi bi-tags-fill', 9),
    (11, 'ข้อมูลค่าชิปปิ้ง', 'N', NULL, '/cost/shipping', 'bi bi-truck', 10),
    (12, 'รายการสั่งซื้อ', 'N', NULL, '/orders', 'bi bi-receipt', 5),
    (13, 'บันทึกรับเงินมัดจำ', 'N', NULL, '/deposit-balance', 'bi bi-cash-stack', 6),
    (14, 'ปฏิทินกำหนดการ', 'N', NULL, '/schedule-calendar', 'bi bi-calendar-event', 1),
    (15, 'รายงาน', 'N', NULL, '/reports', 'bi bi-file-earmark-bar-graph', 11),
    (16, 'บันทึกค่าใช้จ่าย', 'N', NULL, '/cost/expense', 'bi bi-credit-card', 12),
    (17, 'คำนวณราคาขาย', 'N', NULL, '/pricing-calculator', 'bi bi-calculator', 13),
    (18, 'จัดการ Dashboard', 'N', NULL, '/dashboard/manage', 'bi bi-grid-1x2', 14);

INSERT INTO t_order_status VALUES
    (1, 'รอกดของ', 'warning'),
    (2, 'กดของแล้ว รอเข้าโกดัง', 'info'),
    (3, 'รอของถึงร้าน', 'orange'),
    (4, 'ถึงร้านแล้วรอส่ง', 'danger'),
    (5, 'ส่งของสำเร็จ', 'success');

INSERT INTO t_payment_method VALUES
    (1, 'จ่ายเต็ม', 'A'),
    (2, 'มัดจำ', 'A'),
    (3, 'ชำระมัดจำแล้ว', 'D');

INSERT INTO t_payment_type VALUES (1, 'ของถึงไทย'), (2, 'กำหนดวัน');
INSERT INTO t_product_status VALUES (1, 'เปิดพรี'), (2, 'ปิดพรี');

INSERT INTO t_settings (id_setting, s_key, s_value) VALUES
    (1, 'theme_mode', 'dark'),
    (2, 'schedule_show_completed', 'true'),
    (3, 'dashboard_chart_series', 'amount,receivedPaid,pledgePaid,pressCost,shippingCost'),
    (4, 'dashboard_chart_granularity', 'day'),
    (5, 'order_show_closed_products', 'false'),
    (6, 'dashboard_widgets', '[]');

INSERT INTO t_type_cost VALUES
    (1, 'ค่ากดของ'),
    (2, 'ค่าชิปปิ้ง'),
    (3, 'ค่าสั่งกล่อง'),
    (4, 'ค่าสั่งทำของแถม'),
    (5, 'ค่าส่งไปรษณีย์'),
    (99, 'อื่น ๆ');

INSERT INTO t_type_income VALUES
    (1, 'ค่าของ ( จ่ายเต็ม )'),
    (2, 'ค่าของ ( มัดจำ )'),
    (3, 'ยอดมัดจำที่เหลือ'),
    (4, 'ของพร้อมส่ง');

INSERT INTO t_log_version VALUES (1, '1.0.0', '2026-05-21');

SELECT setval(pg_get_serial_sequence('t_group', 'id_group'), COALESCE((SELECT MAX(id_group) FROM t_group), 1));
SELECT setval(pg_get_serial_sequence('t_menu', 'id_menu'), COALESCE((SELECT MAX(id_menu) FROM t_menu), 1));
SELECT setval(pg_get_serial_sequence('t_settings', 'id_setting'), COALESCE((SELECT MAX(id_setting) FROM t_settings), 1));
SELECT setval(pg_get_serial_sequence('t_log_version', 'id_log_version'), COALESCE((SELECT MAX(id_log_version) FROM t_log_version), 1));

CREATE VIEW q_artist AS
SELECT a.id_art, a.a_name, a.id_group, g.g_name, a.a_logo, a.a_delete
FROM t_artist a
JOIN t_group g ON g.id_group = a.id_group;

CREATE VIEW q_cost AS
SELECT c.id_cost, c.c_create_date, c.id_type_cost, tc.tc_name, c.c_price, c.c_note, c.c_delete
FROM t_cost c
JOIN t_type_cost tc ON tc.id_type_cost = c.id_type_cost;

CREATE VIEW q_cover AS
SELECT c.id_cover, c.id_pro, p.p_name, p.id_type, t.t_name, c.id_web, w.w_name, c.id_ver, v.v_name,
       c.c_name, c.c_price_total, c.c_price_pledge, c.c_price_balance, c.c_delete
FROM t_cover c
JOIN t_product p ON p.id_product = c.id_pro
JOIN t_website w ON w.id_web = c.id_web
JOIN t_version v ON v.id_ver = c.id_ver
JOIN t_type t ON t.id_type = p.id_type;

CREATE VIEW q_customer_name AS
SELECT o_customer_name
FROM t_order
GROUP BY o_customer_name;

CREATE VIEW q_group_website AS
SELECT c.id_web, w.w_name, c.id_pro, c.c_delete
FROM t_cover c
JOIN t_website w ON w.id_web = c.id_web
GROUP BY c.id_web, w.w_name, c.id_pro, c.c_delete;

CREATE VIEW q_income AS
SELECT i.id_income, i.c_create_date, i.c_customer_name, i.id_type_income, ti.ti_name,
       i.c_price, i.c_note, i.c_delete, i.id_order
FROM t_income i
JOIN t_type_income ti ON ti.id_type_income = i.id_type_income;

CREATE VIEW q_order AS
SELECT o.id_order, o.o_order_date, o.o_order_code, o.o_customer_name, o.id_pay_method,
       pm.pm_name, o.o_send_cost, o.o_discount, o.o_price_total, o.id_pay_type, pt.pt_name,
       o.o_price_pledge, o.o_price_balance, o.o_last_pay_date, o.o_net, o.o_remark
FROM t_order o
JOIN t_payment_method pm ON pm.id_pay_method = o.id_pay_method
LEFT JOIN t_payment_type pt ON pt.id_pay_type = o.id_pay_type;

CREATE VIEW q_order_detail AS
SELECT od.id_order_detail, od.id_order, o.o_customer_name, c.id_pro, p.p_name, p.id_type, t.t_name,
       p.id_art, a.a_name, c.id_web, w.w_name, c.id_ver, v.v_name, od.id_cover, c.c_name,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_total, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_total,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_pledge, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_pledge,
       TO_CHAR(COALESCE(NULLIF(REPLACE(c.c_price_balance, ',', ''), '')::numeric, 0), 'FM999G999G990') AS c_price_balance,
       od.od_qty,
       TO_CHAR(COALESCE(od.od_price_total, 0), 'FM999G999G990') AS od_price_total,
       TO_CHAR(COALESCE(od.od_price_pledge, 0), 'FM999G999G990') AS od_price_pledge,
       TO_CHAR(COALESCE(od.od_price_balance, 0), 'FM999G999G990') AS od_price_balance,
       od.id_order_status, os.os_name
FROM t_order_detail od
JOIN t_cover c ON c.id_cover = od.id_cover
JOIN t_product p ON p.id_product = c.id_pro
JOIN t_website w ON w.id_web = c.id_web
JOIN t_version v ON v.id_ver = c.id_ver
JOIN t_type t ON t.id_type = p.id_type
JOIN t_artist a ON a.id_art = p.id_art
JOIN t_order_status os ON os.id_order_status = od.id_order_status
LEFT JOIN t_order o ON o.id_order = od.id_order;

CREATE VIEW q_cost_detail AS
SELECT cd.id_cost_detail, qc.id_cost, qc.c_create_date, qc.id_type_cost, qc.tc_name, qc.c_price,
       qc.c_note, qc.c_delete, qod.*
FROM t_cost_detail cd
JOIN q_cost qc ON qc.id_cost = cd.id_cost
JOIN q_order_detail qod ON qod.id_order_detail = cd.id_order_detail;

CREATE VIEW q_product AS
SELECT p.id_product, p.p_name, p.id_type, t.t_name, p.id_art, a.a_name, a.a_logo,
       TO_CHAR(p.p_end_date, 'DD/MM/YYYY') AS p_end_date,
       TO_CHAR(p.p_send_date, 'DD/MM/YYYY') AS p_send_date,
       p.id_pro_status, ps.ps_name, p.p_delete, p.p_pic
FROM t_product p
JOIN t_type t ON t.id_type = p.id_type
JOIN t_artist a ON a.id_art = p.id_art
JOIN t_product_status ps ON ps.id_pro_status = p.id_pro_status;

CREATE VIEW q_product_web AS
SELECT pw.id_pro_web, pw.id_pro, p.p_name, pw.id_web, w.w_name
FROM t_product_web pw
JOIN t_product p ON p.id_product = pw.id_pro
JOIN t_website w ON w.id_web = pw.id_web;

CREATE VIEW q_report_money_cost AS
SELECT c.id_cost AS id_r, c.c_create_date AS r_date, tc.tc_name AS r_name, c.c_price AS r_price,
       c.c_note AS r_note, c.c_delete AS r_delete, 'C' AS r_tpye
FROM t_cost c
JOIN t_type_cost tc ON tc.id_type_cost = c.id_type_cost;

CREATE VIEW q_report_money_income AS
SELECT i.id_income AS id_r, i.c_create_date AS r_date, ti.ti_name AS r_name, i.c_price AS r_price,
       i.c_note AS r_note, i.c_delete AS r_delete, i.id_order, 'I' AS r_tpye
FROM t_income i
JOIN t_type_income ti ON ti.id_type_income = i.id_type_income;

CREATE VIEW q_end_date AS
SELECT TO_CHAR(p_end_date, 'DD/MM/YYYY') AS p_end_date,
       EXTRACT(DAY FROM p_end_date)::integer AS p_end_date_day,
       EXTRACT(MONTH FROM p_end_date)::integer AS p_end_date_month,
       EXTRACT(YEAR FROM p_end_date)::integer AS p_end_date_year,
       id_pro_status, p_delete
FROM t_product;

CREATE VIEW q_send_date AS
SELECT TO_CHAR(p_send_date, 'DD/MM/YYYY') AS p_send_date,
       EXTRACT(DAY FROM p_send_date)::integer AS p_send_date_day,
       EXTRACT(MONTH FROM p_send_date)::integer AS p_send_date_month,
       EXTRACT(YEAR FROM p_send_date)::integer AS p_send_date_year,
       id_pro_status, p_delete
FROM t_product;

BEGIN;
TRUNCATE TABLE t_group, t_artist, t_type, t_website, t_version, t_product_status, t_product, t_cover, t_product_web, t_type_cost, t_cost, t_cost_detail, t_type_income, t_income, t_lot, t_lot_detail, t_menu, t_payment_method, t_payment_type, t_order, t_order_status, t_order_detail, t_sale, t_settings, t_log_version, t_user RESTART IDENTITY CASCADE;

-- Production data converted from MySQL INSERT statements.
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (12, 'I.O.I', 5, 'https://pbs.twimg.com/media/HIq6wAWaYAAZ9fg?format=jpg&name=medium', 'A');
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (13, 'ALPHA DRIVE ONE', 5, 'https://pbs.twimg.com/profile_images/2049503990564765696/sx1fFgsj_400x400.jpg', 'A');
INSERT INTO t_artist (id_art, a_name, id_group, a_logo, a_delete) VALUES (14, 'KRYSTAL', 5, 'https://pbs.twimg.com/media/HIWU138akAAoAqt?format=png&name=small', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (9, '2026-05-16', 1, '1314.33', '', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (10, '2026-05-16', 1, '4222.20', '', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (11, '2026-05-15', 1, '1334', '', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (12, '2026-05-15', 1, '1314.33', '', 'A');
INSERT INTO t_cost (id_cost, c_create_date, id_type_cost, c_price, c_note, c_delete) VALUES (13, '2026-05-16', 1, '2633.20', '', 'A');
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (29, 9, 4);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (30, 9, 9);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (31, 9, 12);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (32, 10, 1);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (33, 10, 2);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (34, 10, 3);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (35, 10, 5);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (36, 10, 6);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (37, 10, 7);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (38, 10, 8);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (39, 10, 10);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (40, 10, 11);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (41, 10, 13);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (42, 11, 14);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (43, 12, 15);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (44, 13, 16);
INSERT INTO t_cost_detail (id_cost_detail, id_cost, id_order_detail) VALUES (45, 13, 17);
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (1, 6, 9, 11, 'PHOTOBOOK ver.', '550.0', '250.0', '300.0', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (2, 6, 10, 11, 'PHOTOBOOK ver.', '550.0', '250.0', '300.0', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (3, 8, 10, 12, 'OFFICIAL LIGHT STICK', '1490.0', '700.0', '790.0', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (4, 7, 11, 13, 'PHOTOBOOK ver.', '550.0', '350.0', '200.0', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (5, 7, 12, 13, 'PHOTOBOOK ver.', '550.0', '350.0', '200.0', 'A');
INSERT INTO t_cover (id_cover, id_pro, id_web, id_ver, c_name, c_price_total, c_price_pledge, c_price_balance, c_delete) VALUES (6, 9, 13, 14, 'Out Box', '250.0', '100.0', '150.0', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (1, 'SM', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (2, 'YG', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (3, 'JYP', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (4, 'HYPE', 'A');
INSERT INTO t_group (id_group, g_name, g_delete) VALUES (5, 'อื่น ๆ', 'A');
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (1, '2026-04-27', '@momeromars', 1, '600', 'จ่ายเต็ม', 'A', 1, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (2, '2026-05-01', '@faypcx', 1, '600', 'จ่ายเต็ม', 'A', 2, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (3, '2026-05-03', 'Line / noggy', 2, '250', 'จ่ายมัดจำ', 'A', 3, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (4, '2026-05-05', '@Firstt_Trades', 2, '500', 'จ่ายมัดจำ', 'A', 4, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (5, '2026-05-07', '@ningningiluvx', 2, '250', 'จ่ายมัดจำ', 'A', 5, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (6, '2026-05-08', 'Line / Pear.r', 2, '250', 'จ่ายมัดจำ', 'A', 6, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (7, '2026-05-09', '@Sonnoah_', 2, '250', 'จ่ายมัดจำ', 'A', 7, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (8, '2026-05-09', '@uninons', 2, '500', 'จ่ายมัดจำ', 'A', 8, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (9, '2026-05-12', '@My_Kyuyok', 2, '250', 'จ่ายมัดจำ', 'A', 9, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (10, '2026-05-16', '@jkjnbear', 2, '500', 'จ่ายมัดจำ', 'A', 10, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (11, '2026-05-23', '@PhonlawatL0ve', 2, '700', 'จ่ายมัดจำ', 'A', 11, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (12, '2026-05-15', '@gwi11_9', 2, '700', 'จ่ายมัดจำ', 'A', 12, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (13, '2026-05-16', '@KariyoungWonna', 2, '700', 'จ่ายมัดจำ', 'A', 13, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (14, '2026-05-16', '@mtno1r', 2, '700', 'จ่ายมัดจำ', 'A', 14, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (15, '2026-05-21', '@mandushot', 1, '600', 'จ่ายเต็ม', 'A', 15, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (16, '2026-05-22', '@bellannabells', 2, '350', 'จ่ายมัดจำ', 'A', 16, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (17, '2026-05-23', '@somebody_rainy', 2, '350', 'จ่ายมัดจำ', 'A', 17, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (18, '2026-05-23', '@bluietny', 2, '350', 'จ่ายมัดจำ', 'A', 18, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (19, '2026-05-23', '@MethawiMnt62564', 2, '350', 'จ่ายมัดจำ', 'A', 19, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (20, '2026-05-15', '@chabarimrua', 2, '100', 'จ่ายมัดจำ', 'A', 20, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (21, '2026-05-15', '@bonosyumi', 2, '100', 'จ่ายมัดจำ', 'A', 21, NULL);
INSERT INTO t_income (id_income, c_create_date, c_customer_name, id_type_income, c_price, c_note, c_delete, id_order, id_sale) VALUES (22, '2026-05-23', '@bluietny', 2, '100', 'จ่ายมัดจำ', 'A', 22, NULL);
INSERT INTO t_lot (id_lot, l_lot_number, l_create_date, l_start_date, l_end_date, l_arrive_date, l_delete) VALUES (1, '237', '2026-05-21', '2026-06-10', '2026-06-15', NULL, 'A');
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (1, 1, 14);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (2, 1, 15);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (3, 1, 16);
INSERT INTO t_lot_detail (id_lot_detail, id_lot, id_order_detail) VALUES (4, 1, 17);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (2, 'ข้อมูลพื้นฐาน', 'Y', NULL, NULL, 'bi bi-stack', 2);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (3, 'ข้อมูลศิลปิน', NULL, 2, '/artist', NULL, 1);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (4, 'ข้อมูลประเภทสินค้า', NULL, 2, '/type', NULL, 2);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (5, 'ข้อมูลเว็บไซต์', NULL, 2, '/website', NULL, 3);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (6, 'ข้อมูลสินค้า', 'N', NULL, '/product', 'bi bi-book-half', 4);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (7, 'บันทึกออร์เดอร์', 'N', NULL, '/order', 'bi bi-basket', 5);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (8, 'อัปเดทสถานะ', 'N', NULL, '/change', 'bi bi-check-circle-fill', 8);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (9, 'ข้อมูลการกดของ', 'N', NULL, '/check_status_2', 'bi bi-clipboard-check', 9);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (10, 'ข้อมูล LOT', 'N', NULL, '/lot', 'bi bi-tags-fill', 10);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (11, 'ข้อมูลค่าชิปปิ้ง', 'N', NULL, '/cost/shipping', 'bi bi-truck', 11);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (12, 'รายการสั่งซื้อ', 'N', NULL, '/orders', 'bi bi-receipt', 6);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (13, 'บันทึกรับเงินมัดจำ', 'N', NULL, '/deposit-balance', 'bi bi-cash-stack', 7);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (14, 'ปฏิทินกำหนดการ', 'N', NULL, '/schedule-calendar', 'bi bi-calendar-event', 1);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (15, 'รายงาน', 'N', NULL, '/reports', 'bi bi-file-earmark-bar-graph', 12);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (16, 'บันทึกค่าใช้จ่าย', 'N', NULL, '/cost/expense', 'bi bi-credit-card', 13);
INSERT INTO t_menu (id_menu, m_name, m_parent, m_id_menu, m_url, m_icon, m_order) VALUES (17, 'คำนวณราคาขาย', 'N', NULL, '/pricing-calculator', 'bi bi-calculator', 3);
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (1, '2026-04-27', 'PR-26-000001', '@momeromars', 1, NULL, NULL, 50, 0, 550, 0, 0, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (2, '2026-05-01', 'PR-26-000002', '@faypcx', 1, NULL, NULL, 50, 0, 550, 0, 0, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (3, '2026-05-03', 'PR-26-000003', 'Line / noggy', 2, 1, NULL, 50, 0, 550, 250, 350, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (4, '2026-05-05', 'PR-26-000004', '@Firstt_Trades', 2, 1, NULL, 50, 0, 1100, 500, 650, 1150, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (5, '2026-05-07', 'PR-26-000005', '@ningningiluvx', 2, 1, NULL, 50, 0, 550, 250, 350, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (6, '2026-05-08', 'PR-26-000006', 'Line / Pear.r', 2, 1, NULL, 50, 0, 550, 250, 350, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (7, '2026-05-09', 'PR-26-000007', '@Sonnoah_', 2, 1, NULL, 50, 0, 550, 250, 350, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (8, '2026-05-09', 'PR-26-000008', '@uninons', 2, 1, NULL, 50, 0, 1100, 500, 650, 1150, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (9, '2026-05-12', 'PR-26-000009', '@My_Kyuyok', 1, 1, NULL, 50, 0, 550, 0, 0, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (10, '2026-05-16', 'PR-26-000010', '@jkjnbear', 2, 1, NULL, 50, 0, 1100, 500, 650, 1150, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (11, '2026-05-15', 'PR-26-000011', '@PhonlawatL0ve', 2, 1, NULL, 60, 0, 1490, 700, 850, 1550, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (12, '2026-05-15', 'PR-26-000012', '@gwi11_9', 2, 1, NULL, 60, 0, 1490, 700, 850, 1550, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (13, '2026-05-16', 'PR-26-000013', '@KariyoungWonna', 2, 1, NULL, 60, 0, 1490, 700, 850, 1550, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (14, '2026-05-16', 'PR-26-000014', '@mtno1r', 2, 1, NULL, 60, 0, 1490, 700, 850, 1550, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (15, '2026-05-21', 'PR-26-000015', '@mandushot', 1, NULL, NULL, 50, 0, 550, 0, 0, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (16, '2026-05-22', 'PR-26-000016', '@bellannabells', 2, 1, NULL, 50, 0, 550, 350, 250, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (17, '2026-05-23', 'PR-26-000017', '@somebody_rainy', 2, 1, NULL, 50, 0, 550, 350, 250, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (18, '2026-05-23', 'PR-26-000018', '@bluietny', 2, 1, NULL, 50, 0, 550, 350, 250, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (19, '2026-05-23', 'PR-26-000019', '@MethawiMnt62564', 2, 1, NULL, 50, 0, 550, 350, 250, 600, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (20, '2026-05-15', 'PR-26-000020', '@chabarimrua', 2, 1, NULL, 50, 0, 250, 100, 200, 300, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (21, '2026-05-15', 'PR-26-000021', '@bonosyumi', 2, 1, NULL, 50, 0, 250, 100, 200, 300, '');
INSERT INTO t_order (id_order, o_order_date, o_order_code, o_customer_name, id_pay_method, id_pay_type, o_last_pay_date, o_send_cost, o_discount, o_price_total, o_price_pledge, o_price_balance, o_net, o_remark) VALUES (22, '2026-05-23', 'PR-26-000022', '@bluietny', 2, 1, NULL, 0, 0, 250, 100, 150, 250, '');
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (1, 1, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (2, 2, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (3, 3, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (4, 4, 1, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (5, 4, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (6, 5, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (7, 6, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (8, 7, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (9, 8, 1, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (10, 8, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (11, 9, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (12, 10, 1, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (13, 10, 2, 1, 550, 250, 300, 2);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (14, 11, 3, 1, 1490, 700, 790, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (15, 12, 3, 1, 1490, 700, 790, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (16, 13, 3, 1, 1490, 700, 790, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (17, 14, 3, 1, 1490, 700, 790, 3);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (18, 15, 4, 1, 550, 350, 200, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (19, 16, 4, 1, 550, 350, 200, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (20, 17, 4, 1, 550, 350, 200, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (21, 18, 4, 1, 550, 350, 200, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (22, 19, 4, 1, 550, 350, 200, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (23, 20, 6, 1, 250, 100, 150, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (24, 21, 6, 1, 250, 100, 150, 1);
INSERT INTO t_order_detail (id_order_detail, id_order, id_cover, od_qty, od_price_total, od_price_pledge, od_price_balance, id_order_status) VALUES (25, 22, 6, 1, 250, 100, 150, 1);
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (1, 'รอกดของ', 'warning');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (2, 'กดของแล้ว รอเข้าโกดัง', 'info');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (3, 'รอของถึงร้าน', 'orange');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (4, 'ถึงร้านแล้วรอส่ง', 'danger');
INSERT INTO t_order_status (id_order_status, os_name, os_color) VALUES (5, 'ส่งของสำเร็จ', 'success');
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (1, 'จ่ายเต็ม', 'A');
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (2, 'มัดจำ', 'A');
INSERT INTO t_payment_method (id_pay_method, pm_name, pm_delete) VALUES (3, 'ชำระมัดจำแล้ว', 'A');
INSERT INTO t_payment_type (id_pay_type, pt_name) VALUES (1, 'ของถึงไทย');
INSERT INTO t_payment_type (id_pay_type, pt_name) VALUES (2, 'กำหนดวัน');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (6, 'I.O.I 3RD MINI ALBUM [I.O.I : LOOP]', 7, 12, '2026-05-14', '2026-06-03', 1, 'A', 'https://pbs.twimg.com/media/HG6vaksaMAAos2z?format=jpg&name=medium');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (7, 'I.O.I 3RD MINI ALBUM [I.O.I : LOOP]', 8, 12, '2026-05-25', '2026-06-30', 1, 'A', 'https://pbs.twimg.com/media/HIxG7CmbYAAI5dI?format=jpg&name=medium');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (8, 'ALPHA DRIVE ONE OFFICIAL LIGHT STICK', 9, 13, '2026-12-31', '2026-12-31', 1, 'A', 'https://pbs.twimg.com/media/HIVowbNbYAEIAu5?format=jpg&name=medium');
INSERT INTO t_product (id_product, p_name, id_type, id_art, p_end_date, p_send_date, id_pro_status, p_delete, p_pic) VALUES (9, 'KRYSTAL [PWLT]', 7, 14, '2026-05-26', '2026-05-27', 1, 'A', 'https://pbs.twimg.com/media/HIWU138akAAoAqt?format=png&name=small');
INSERT INTO t_product_status (id_pro_status, ps_name) VALUES (1, 'เปิดพรี');
INSERT INTO t_product_status (id_pro_status, ps_name) VALUES (2, 'ปิดพรี');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (1, 'theme_mode', 'light');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (2, 'schedule_show_completed', 'true');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (3, 'dashboard_chart_series', 'amount,receivedPaid,pledgePaid,pressCost,shippingCost');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (4, 'dashboard_chart_granularity', 'day');
INSERT INTO t_settings (id_setting, s_key, s_value) VALUES (5, 'order_show_closed_products', 'true');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (7, 'PRE-ORDER', 'A');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (8, 'LUCKY DRAW', 'A');
INSERT INTO t_type (id_type, t_name, t_delete) VALUES (9, 'LIGHT STICK', 'A');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (1, 'ค่ากดของ');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (2, 'ค่าชิปปิ้ง');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (3, 'ค่าสั่งกล่อง');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (4, 'ค่าสั่งทำของแถม');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (5, 'ค่าส่งไปรษณีย์');
INSERT INTO t_type_cost (id_type_cost, tc_name) VALUES (99, 'อื่น ๆ');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (1, 'ค่าของ ( จ่ายเต็ม )');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (2, 'ค่าของ ( มัดจำ )');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (3, 'ยอดมัดจำที่เหลือ');
INSERT INTO t_type_income (id_type_income, ti_name) VALUES (4, 'ของพร้อมส่ง');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (11, 6, 'PHOTOBOOK ver.', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (12, 8, 'OFFICIAL LIGHT STICK', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (13, 7, 'PHOTOBOOK ver.', 'A');
INSERT INTO t_version (id_ver, id_pro, v_name, v_delete) VALUES (14, 9, 'Out Box', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (9, 'Aladin', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (10, 'YES24', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (11, 'Applemusic', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (12, 'Soundwave', 'A');
INSERT INTO t_website (id_web, w_name, w_delete) VALUES (13, 'Ktown4u', 'A');
INSERT INTO t_log_version (id_log_version, lv_version, lv_date) VALUES (1, '1.0.0', '2026-05-21');

-- Reset identity sequences after explicit id imports.
SELECT setval(pg_get_serial_sequence('t_group', 'id_group'), COALESCE((SELECT MAX(id_group) FROM t_group), 1));
SELECT setval(pg_get_serial_sequence('t_artist', 'id_art'), COALESCE((SELECT MAX(id_art) FROM t_artist), 1));
SELECT setval(pg_get_serial_sequence('t_type', 'id_type'), COALESCE((SELECT MAX(id_type) FROM t_type), 1));
SELECT setval(pg_get_serial_sequence('t_website', 'id_web'), COALESCE((SELECT MAX(id_web) FROM t_website), 1));
SELECT setval(pg_get_serial_sequence('t_version', 'id_ver'), COALESCE((SELECT MAX(id_ver) FROM t_version), 1));
SELECT setval(pg_get_serial_sequence('t_product', 'id_product'), COALESCE((SELECT MAX(id_product) FROM t_product), 1));
SELECT setval(pg_get_serial_sequence('t_cover', 'id_cover'), COALESCE((SELECT MAX(id_cover) FROM t_cover), 1));
SELECT setval(pg_get_serial_sequence('t_product_web', 'id_pro_web'), COALESCE((SELECT MAX(id_pro_web) FROM t_product_web), 1));
SELECT setval(pg_get_serial_sequence('t_cost', 'id_cost'), COALESCE((SELECT MAX(id_cost) FROM t_cost), 1));
SELECT setval(pg_get_serial_sequence('t_cost_detail', 'id_cost_detail'), COALESCE((SELECT MAX(id_cost_detail) FROM t_cost_detail), 1));
SELECT setval(pg_get_serial_sequence('t_income', 'id_income'), COALESCE((SELECT MAX(id_income) FROM t_income), 1));
SELECT setval(pg_get_serial_sequence('t_lot', 'id_lot'), COALESCE((SELECT MAX(id_lot) FROM t_lot), 1));
SELECT setval(pg_get_serial_sequence('t_lot_detail', 'id_lot_detail'), COALESCE((SELECT MAX(id_lot_detail) FROM t_lot_detail), 1));
SELECT setval(pg_get_serial_sequence('t_menu', 'id_menu'), COALESCE((SELECT MAX(id_menu) FROM t_menu), 1));
SELECT setval(pg_get_serial_sequence('t_order', 'id_order'), COALESCE((SELECT MAX(id_order) FROM t_order), 1));
SELECT setval(pg_get_serial_sequence('t_order_detail', 'id_order_detail'), COALESCE((SELECT MAX(id_order_detail) FROM t_order_detail), 1));
SELECT setval(pg_get_serial_sequence('t_sale', 'id_sale'), COALESCE((SELECT MAX(id_sale) FROM t_sale), 1));
SELECT setval(pg_get_serial_sequence('t_settings', 'id_setting'), COALESCE((SELECT MAX(id_setting) FROM t_settings), 1));
SELECT setval(pg_get_serial_sequence('t_log_version', 'id_log_version'), COALESCE((SELECT MAX(id_log_version) FROM t_log_version), 1));
SELECT setval(pg_get_serial_sequence('t_user', 'id_user'), COALESCE((SELECT MAX(id_user) FROM t_user), 1));
COMMIT;
