spring.application.name=preorder
spring.profiles.default=local

spring.datasource.username=neondb_owner
spring.datasource.password=npg_gHJQ3kbuiKf5
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.jdbc.datasource.DataSourceUtils=debug
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false
