spring.application.name=preorder

spring.datasource.url=jdbc:mysql://localhost:3306/db_sriundee_shop?createDatabaseIfNotExist=true
spring.datasource.username=sriundee_shop
spring.datasource.password=sriundee_shop
#spring.datasource.url=jdbc:mysql://34.87.89.214:3306/db_sriundee_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=Da9EIqd.E8LM+UR^
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.jdbc.datasource.DataSourceUtils=debug
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false