package com.sriundee.preorder.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;

@Component
public class LoginDatabaseInitializer {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void initialize() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS t_user (
                    ID_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    u_username varchar(255),
                    u_delete varchar(255)
                )
                """);
        jdbcTemplate.execute("ALTER TABLE t_settings ADD COLUMN IF NOT EXISTS ID_user integer");
        jdbcTemplate.execute("ALTER TABLE t_settings DROP CONSTRAINT IF EXISTS uq_t_settings_key");
        jdbcTemplate.execute("DROP INDEX IF EXISTS idx_t_settings_key");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_t_settings_key_user ON t_settings (s_key, ID_user)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_t_user_username ON t_user (LOWER(u_username))");
    }
}
